import { chromium } from "playwright";
import { resolve } from "node:path";
const OUT = process.env.OUT;
const READY = () => Boolean(window.__composition_STORE__ && window.__composition_STORE__.getState().currentPageId && document.querySelector(".app:not(.builder-booting)") && document.querySelector('[data-testid="skia-canvas-unified"]'));
const browser = await chromium.launch({ headless: false });
const page = await (await browser.newContext({ storageState: resolve("apps/builder/scripts/.auth-session.json"), viewport: { width: 1600, height: 1400 }, deviceScaleFactor: 2 })).newPage();
const errors = []; page.on("pageerror", (e) => errors.push(e.message));
await page.goto("http://localhost:5173/dashboard", { waitUntil: "networkidle" });
const b = page.locator("button.dashboard-create-button").first(); await b.waitFor({ state: "visible", timeout: 15000 }); await b.click();
const i = page.locator("#new-project-name"); await i.waitFor({ state: "visible" }); await i.fill(`db-${Date.now()}`); await i.press("Enter");
await page.waitForURL(/\/builder\/[^/?]+$/, { timeout: 60000 }); await page.waitForFunction(READY, undefined, { timeout: 90000 }); await page.waitForTimeout(1200);
const panel = async (name, want) => { const btn = page.getByRole("button", { name, exact: true }).first(); const pressed = await btn.getAttribute("aria-pressed"); if ((pressed === "true") !== want) { await btn.click(); await page.waitForTimeout(400); } };
const P = '[data-panel-id="properties"]';
await panel("Components", true);
const item = page.locator("button.list-item").filter({ has: page.locator(".list-item-name", { hasText: /^List ?Box$/i }) }).first();
await item.scrollIntoViewIfNeeded(); await item.click(); await page.waitForTimeout(900);
await panel("Components", false); await panel("Properties", true); await page.waitForTimeout(400);
await page.evaluate((P) => { document.querySelectorAll(`${P} .section-caret[aria-expanded="false"]`).forEach((c) => c.click()); }, P); await page.waitForTimeout(300);
const row = page.locator(`${P} .fieldset-row`).filter({ has: page.locator(".actions-binding") }).first();
console.log("row", JSON.stringify(await row.boundingBox()));
const geo = await row.evaluate((r) => { const fs = r.querySelector("fieldset"); const act = r.querySelector(".actions-binding button"); const sel = r.querySelector(".binding-name-select, .binding-empty"); const f = fs.getBoundingClientRect(), a = act.getBoundingClientRect(), s = sel.getBoundingClientRect(); return { fieldset: `${Math.round(f.width)}×${Math.round(f.height)}`, action: `${Math.round(a.width)}×${Math.round(a.height)} top=${Math.round(a.top)} right=${Math.round(a.right)}`, select: `top=${Math.round(s.top)} h=${Math.round(s.height)}`, textButtons: Array.from(fs.querySelectorAll("button")).map((b) => b.textContent.trim()).filter(Boolean), label: act.getAttribute("aria-label") }; });
console.log("geo", JSON.stringify(geo));
await row.screenshot({ path: `${OUT}/data-row.png` });
const bb = await page.locator(`${P} .actions-binding button`).boundingBox(); await page.mouse.move(bb.x - 40, bb.y + 14); await page.mouse.move(bb.x + 10, bb.y + 14, { steps: 8 }); await page.waitForTimeout(1600);
console.log("tooltip", await page.evaluate(() => document.querySelector('[role="tooltip"]')?.textContent?.trim()));
await page.locator(`${P} .actions-binding button`).click(); await page.waitForTimeout(800);
console.log("creator", await page.evaluate(() => { const st = document.querySelector('[data-panel-id="datatable"], [data-panel="datatable"]'); return { editorOpen: Boolean(document.querySelector(".datatable-creator, [class*='creator']")), title: document.querySelector("[class*='creator'] h2, [class*='creator'] .panel-title")?.textContent?.trim() }; }));
await page.screenshot({ path: `${OUT}/after-click.png` });
console.log("errors", errors.slice(0, 5));
await browser.close();
