import { chromium } from "playwright";
import { resolve } from "node:path";
const READY = () => Boolean(window.__composition_STORE__ && window.__composition_STORE__.getState().currentPageId && document.querySelector(".app:not(.builder-booting)") && document.querySelector('[data-testid="skia-canvas-unified"]'));
const browser = await chromium.launch({ headless: true });
const page = await (await browser.newContext({ storageState: resolve("apps/builder/scripts/.auth-session.json"), viewport: { width: 1600, height: 1400 } })).newPage();
await page.goto("http://localhost:5173/dashboard", { waitUntil: "networkidle" });
const b = page.locator("button.dashboard-create-button").first(); await b.waitFor({ state: "visible", timeout: 15000 }); await b.click();
const i = page.locator("#new-project-name"); await i.waitFor({ state: "visible" }); await i.fill(`it-${Date.now()}`); await i.press("Enter");
await page.waitForURL(/\/builder\/[^/?]+$/, { timeout: 60000 }); await page.waitForFunction(READY, undefined, { timeout: 90000 }); await page.waitForTimeout(1200);
const panel = async (name, want) => { const btn = page.getByRole("button", { name, exact: true }).first(); const pressed = await btn.getAttribute("aria-pressed"); if ((pressed === "true") !== want) { await btn.click(); await page.waitForTimeout(400); } };
await panel("Components", true); await page.locator("button.list-item").filter({ has: page.locator(".list-item-name", { hasText: /^Popover$/i }) }).first().click(); await page.waitForTimeout(800); await panel("Components", false); await panel("Properties", true); await page.waitForTimeout(400);
const P = '[data-panel-id="properties"]';
await page.evaluate((P) => { document.querySelectorAll(`${P} .section-caret[aria-expanded="false"]`).forEach((c) => c.click()); }, P); await page.waitForTimeout(300);
console.log(await page.evaluate((P) => Array.from(document.querySelectorAll(`${P} .react-aria-ToggleButtonGroup[data-indicator="true"]`)).map((g) => { const ind = g.querySelector(".react-aria-SelectionIndicator"); const cs = ind ? getComputedStyle(ind) : null; return `${g.getAttribute("aria-label")}: transitionProperty=${cs?.transitionProperty} duration=${cs?.transitionDuration} position=${cs?.position}`; }), P));
await panel("Properties", false); await panel("Styles", true); await page.waitForTimeout(500);
const S = '[data-panel-id="styles"]';
await page.evaluate((S) => { document.querySelectorAll(`${S} .section-caret[aria-expanded="false"]`).forEach((c) => c.click()); }, S); await page.waitForTimeout(300);
console.log(await page.evaluate((S) => Array.from(document.querySelectorAll(`${S} .react-aria-ToggleButtonGroup[data-indicator="true"]`)).slice(0, 4).map((g) => { const ind = g.querySelector(".react-aria-SelectionIndicator"); const cs = ind ? getComputedStyle(ind) : null; return `${g.getAttribute("aria-label")}: transitionProperty=${cs?.transitionProperty} duration=${cs?.transitionDuration}`; }), S));
await browser.close();
