import { chromium } from "playwright";
import { resolve } from "node:path";
const READY = () => Boolean(window.__composition_STORE__ && window.__composition_STORE__.getState().currentPageId && document.querySelector(".app:not(.builder-booting)") && document.querySelector('[data-testid="skia-canvas-unified"]'));
const browser = await chromium.launch({ headless: true });
const page = await (await browser.newContext({ storageState: resolve("apps/builder/scripts/.auth-session.json"), viewport: { width: 1600, height: 1400 } })).newPage();
await page.goto("http://localhost:5173/dashboard", { waitUntil: "networkidle" });
const b = page.locator("button.dashboard-create-button").first(); await b.waitFor({ state: "visible", timeout: 15000 }); await b.click();
const i = page.locator("#new-project-name"); await i.waitFor({ state: "visible" }); await i.fill(`pl-${Date.now()}`); await i.press("Enter");
await page.waitForURL(/\/builder\/[^/?]+$/, { timeout: 60000 }); await page.waitForFunction(READY, undefined, { timeout: 90000 }); await page.waitForTimeout(1200);
const panel = async (name, want) => { const btn = page.getByRole("button", { name, exact: true }).first(); const pressed = await btn.getAttribute("aria-pressed"); if ((pressed === "true") !== want) { await btn.click(); await page.waitForTimeout(400); } };
await panel("Components", true); await page.locator("button.list-item").filter({ has: page.locator(".list-item-name", { hasText: /^Popover$/i }) }).first().click(); await page.waitForTimeout(800); await panel("Components", false); await panel("Properties", true); await page.waitForTimeout(400);
const P = '[data-panel-id="properties"]';
await page.evaluate((P) => { document.querySelectorAll(`${P} .section-caret[aria-expanded="false"]`).forEach((c) => c.click()); }, P); await page.waitForTimeout(300);
const G = `${P} .property-placement .react-aria-ToggleButtonGroup`;
await page.evaluate((G) => { const g = document.querySelector(G); window.__g = g; window.__btns = Array.from(g.querySelectorAll(".react-aria-ToggleButton")); window.__btns.forEach((b, i) => (b.dataset.probeIdx = String(i))); window.__log = []; const mo = new MutationObserver((ms) => { for (const m of ms) { for (const n of m.addedNodes) if (n.nodeType === 1) window.__log.push(`+${n.className} sel=${n.getAttribute("data-selected")} entering=${n.getAttribute("data-entering")}`); for (const n of m.removedNodes) if (n.nodeType === 1) window.__log.push(`-${n.className} sel=${n.getAttribute("data-selected")} exiting=${n.getAttribute("data-exiting")}`); if (m.type === "attributes") window.__log.push(`~${m.target.className.split(" ")[0]}.${m.attributeName}=${m.target.getAttribute(m.attributeName)} translate=${m.target.style?.translate}`); } }); mo.observe(g, { childList: true, subtree: true, attributes: true, attributeFilter: ["data-selected", "style", "data-entering", "data-exiting"] }); console.log("selected before", g.querySelector("[data-selected]")?.getAttribute("aria-label"), Boolean(g.querySelector("[data-selected] .react-aria-SelectionIndicator"))); }, G);
await page.locator(G).locator(".react-aria-ToggleButton").nth(0).click(); await page.waitForTimeout(500);
console.log(await page.evaluate((G) => { const g = document.querySelector(G); const btns = Array.from(g.querySelectorAll(".react-aria-ToggleButton")); return { sameGroup: g === window.__g, sameButtons: btns.every((b, i) => b === window.__btns[i]), selected: g.querySelector("[data-selected]")?.getAttribute("aria-label"), log: window.__log.slice(0, 30) }; }, G));
await browser.close();
