import { chromium } from "playwright";
import { resolve } from "node:path";
const OUT = process.env.OUT;
const READY = () => Boolean(window.__composition_STORE__ && window.__composition_STORE__.getState().currentPageId && document.querySelector(".app:not(.builder-booting)") && document.querySelector('[data-testid="skia-canvas-unified"]'));
const browser = await chromium.launch({ headless: false });
const page = await (await browser.newContext({ storageState: resolve("apps/builder/scripts/.auth-session.json"), viewport: { width: 1600, height: 1400 }, deviceScaleFactor: 2 })).newPage();
const errors = []; page.on("pageerror", (e) => errors.push(e.message));
await page.goto("http://localhost:5173/dashboard", { waitUntil: "networkidle" });
const b = page.locator("button.dashboard-create-button").first(); await b.waitFor({ state: "visible", timeout: 15000 }); await b.click();
const i = page.locator("#new-project-name"); await i.waitFor({ state: "visible" }); await i.fill(`rs-${Date.now()}`); await i.press("Enter");
await page.waitForURL(/\/builder\/[^/?]+$/, { timeout: 60000 }); await page.waitForFunction(READY, undefined, { timeout: 90000 }); await page.waitForTimeout(1200);
const panel = async (name, want) => { const btn = page.getByRole("button", { name, exact: true }).first(); const pressed = await btn.getAttribute("aria-pressed"); if ((pressed === "true") !== want) { await btn.click(); await page.waitForTimeout(400); } };
const P = '[data-panel-id="properties"]';
await panel("Components", true); const item = page.locator("button.list-item").filter({ has: page.locator(".list-item-name", { hasText: /^Button$/i }) }).first(); await item.click(); await page.waitForTimeout(800); await panel("Components", false); await panel("Properties", true); await page.waitForTimeout(400);
await page.evaluate((P) => { document.querySelectorAll(`${P} .section-caret[aria-expanded="false"]`).forEach((c) => c.click()); }, P); await page.waitForTimeout(300);
const count = () => page.locator(`${P} .actions-reset`).count();
console.log("fresh reset count", await count());
// change Size via seg → lg
await page.locator(`${P} .property-seg .react-aria-ToggleButton`).filter({ hasText: /^LG$|^lg$|^L$/i }).first().click().catch(async () => { await page.locator(`${P} .property-seg .react-aria-ToggleButton`).nth(3).click(); }); await page.waitForTimeout(500);
const st = await page.evaluate(() => { const s = window.__composition_STORE__.getState(); return s.elementsMap.get(s.selectedElementId).props.size; }); console.log("size now", st, "reset count", await count());
const rb = page.locator(`${P} .actions-reset button`).first(); console.log("reset label", await rb.getAttribute("aria-label"), JSON.stringify(await rb.boundingBox()));
const row = page.locator(`${P} .fieldset-row`).filter({ has: page.locator(".actions-reset") }).first(); await row.screenshot({ path: `${OUT}/row-dirty.png` });
const bb = await rb.boundingBox(); await page.mouse.move(bb.x - 40, bb.y + 14); await page.mouse.move(bb.x + 10, bb.y + 14, { steps: 8 }); await page.waitForTimeout(1600);
console.log("tooltip", await page.evaluate(() => document.querySelector('[role="tooltip"]')?.textContent?.trim()));
await rb.click(); await page.waitForTimeout(600);
console.log("after reset size", await page.evaluate(() => { const s = window.__composition_STORE__.getState(); return s.elementsMap.get(s.selectedElementId).props.size; }), "reset count", await count());
// number field (Popover offset) — add popover
await panel("Components", true); await page.locator("button.list-item").filter({ has: page.locator(".list-item-name", { hasText: /^Popover$/i }) }).first().click(); await page.waitForTimeout(800); await panel("Components", false); await panel("Properties", true); await page.waitForTimeout(400);
await page.evaluate((P) => { document.querySelectorAll(`${P} .section-caret[aria-expanded="false"]`).forEach((c) => c.click()); }, P); await page.waitForTimeout(300);
console.log("popover fresh reset count", await count());
console.log("errors", errors.slice(0, 5));
await browser.close();
