import { chromium } from "playwright";
import { resolve } from "node:path";
const READY = () => Boolean(window.__composition_STORE__ && window.__composition_STORE__.getState().currentPageId && document.querySelector(".app:not(.builder-booting)") && document.querySelector('[data-testid="skia-canvas-unified"]'));
const browser = await chromium.launch({ headless: false });
const page = await (await browser.newContext({ storageState: resolve("apps/builder/scripts/.auth-session.json"), viewport: { width: 1600, height: 1400 } })).newPage();
const errors = []; page.on("pageerror", (e) => errors.push(String(e))); page.on("console", (m) => { if (m.type() === "error") errors.push(m.text().slice(0, 200)); if (m.text().startsWith("[probe]")) console.log(m.text()); });
await page.goto("http://localhost:5173/dashboard", { waitUntil: "networkidle" });
const b = page.locator("button.dashboard-create-button").first(); await b.waitFor({ state: "visible" }); await b.click();
const i = page.locator("#new-project-name"); await i.waitFor({ state: "visible" }); await i.fill(`wig-${Date.now()}`); await i.press("Enter");
await page.waitForURL(/\/builder\/[^/?]+$/, { timeout: 60000 }); await page.waitForFunction(READY, undefined, { timeout: 90000 }); await page.waitForTimeout(1200);
const panel = async (name, want) => { const btn = page.getByRole("button", { name, exact: true }).first(); const pressed = await btn.getAttribute("aria-pressed"); if ((pressed === "true") !== want) { await btn.click(); await page.waitForTimeout(400); } };
await panel("Components", true); await page.locator("button.list-item").filter({ has: page.locator(".list-item-name", { hasText: /^Button$/i }) }).first().click(); await page.waitForTimeout(800); await panel("Components", false); await panel("Properties", true); await page.waitForTimeout(400);
const P = '[data-panel-id="properties"]';
await page.evaluate((P) => { document.querySelectorAll(`${P} .section-caret[aria-expanded="false"]`).forEach((c) => c.click()); }, P); await page.waitForTimeout(300);
await page.evaluate(() => { document.addEventListener("click", (e) => { const t = e.target; if (t.closest?.('[role="option"]')) console.log("[probe] click reached option", t.closest('[role="option"]').id, "detail", e.detail, e.constructor.name); }, true); document.addEventListener("react-aria-item-action", (e) => console.log("[probe] item-action", e.target.id), true); });
const trig = page.locator(`${P} .icon-picker-input-trigger`).first(); await trig.scrollIntoViewIfNeeded(); await trig.click(); await page.waitForTimeout(600);
console.log("tree:", await page.evaluate(() => { const g = document.querySelector(".icon-picker-grid"); const desc = (el, d) => { const r = el.getBoundingClientRect(); const cs = getComputedStyle(el); return `${"  ".repeat(d)}${el.tagName} role=${el.getAttribute("role")} cls=${el.className} ${Math.round(r.width)}x${Math.round(r.height)} ov=${cs.overflowY} pos=${cs.position} style=${el.getAttribute("style")}`; }; const out = [desc(g, 0)]; let lvl = [g]; for (let d = 1; d <= 3; d++) { const next = []; for (const e of lvl) for (const c of Array.from(e.children).slice(0, 2)) { out.push(desc(c, d)); next.push(c); } lvl = next; } out.push("listbox:", desc(document.querySelector('[role="listbox"]'), 0)); return out.join("\n"); }));
console.log("dom:", await page.evaluate(() => { const g = document.querySelector(".icon-picker-grid"); const o = g.querySelector('[role="option"]'); const chain = []; let el = o; while (el && el !== g) { chain.push(`${el.tagName}.${el.className} style=${el.getAttribute("style")}`); el = el.parentElement; } return { grid: `${g.tagName} style=${g.getAttribute("style")} overflow=${getComputedStyle(g).overflowY}`, chain, gridParent: `${g.parentElement.tagName}.${g.parentElement.className} style=${g.parentElement.getAttribute("style")}` }; }));
await page.keyboard.type("arrow"); await page.waitForTimeout(500);
await page.keyboard.press("ArrowDown"); await page.waitForTimeout(150);
await page.keyboard.press("ArrowDown"); await page.waitForTimeout(150);
await page.keyboard.press("ArrowDown"); await page.waitForTimeout(150);
await page.keyboard.press("ArrowDown"); await page.waitForTimeout(150);
await page.keyboard.press("ArrowDown"); await page.waitForTimeout(150);
await page.keyboard.press("ArrowDown"); await page.waitForTimeout(150);
await page.keyboard.press("ArrowDown"); await page.waitForTimeout(150);
await page.keyboard.press("ArrowDown"); await page.waitForTimeout(150);
await page.keyboard.press("ArrowDown"); await page.waitForTimeout(400);
console.log("9×↓:", JSON.stringify(await page.evaluate(() => { const g = document.querySelector(".icon-picker-grid"); const f = g?.querySelector("[data-focused]"); const r = f?.getBoundingClientRect(); const gr = g.getBoundingClientRect(); return { scrollTop: g?.scrollTop, focusedId: f?.id, inView: r ? r.top >= gr.top && r.bottom <= gr.bottom : null, top: r ? Math.round(r.top - gr.top) : null }; })));
await page.keyboard.press("Enter"); await page.waitForTimeout(800);
console.log("Enter → grid gone:", await page.evaluate(() => !document.querySelector(".icon-picker-grid")), "value:", await page.evaluate((P) => document.querySelector(`${P} .icon-picker-value`)?.textContent, P));
console.log("errors:", errors);
await browser.close();
