import { chromium } from "playwright";
import { resolve } from "node:path";
const OUT = process.env.OUT ?? "/tmp/claude-501/cp2";
const READY = () => Boolean(window.__composition_STORE__ && window.__composition_STORE__.getState().currentPageId && document.querySelector(".app:not(.builder-booting)") && document.querySelector('[data-testid="skia-canvas-unified"]'));
const browser = await chromium.launch({ headless: false });
const page = await (await browser.newContext({ storageState: resolve("apps/builder/scripts/.auth-session.json"), viewport: { width: 1600, height: 1400 }, deviceScaleFactor: 2 })).newPage();
const errors = []; page.on("pageerror", e => errors.push(e.message));
await page.goto("http://localhost:5173/dashboard", { waitUntil: "networkidle" });
const b = page.locator("button.dashboard-create-button").first(); await b.waitFor({ state: "visible", timeout: 15000 }); await b.click();
const i = page.locator("#new-project-name"); await i.waitFor({ state: "visible" }); await i.fill(`cr-${Date.now()}`); await i.press("Enter");
await page.waitForURL(/\/builder\/[^/?]+$/, { timeout: 60000 }); await page.waitForFunction(READY, undefined, { timeout: 90000 }); await page.waitForTimeout(1200);
const M = (sel, n = 14) => page.evaluate(({ sel, n }) => Array.from(document.querySelectorAll(sel)).filter(el => el.getBoundingClientRect().width > 0).slice(0, n).map(el => { const r = el.getBoundingClientRect(); const cs = getComputedStyle(el); return `${el.className.toString().replace(/react-aria-/g,'').slice(0, 40)} | ${Math.round(r.width)}×${Math.round(r.height)} fs${cs.fontSize}`; }), { sel, n });
const P = '[data-panel-id="datatableEditor"]';
const panel = () => page.locator(P).last();
const shot = async (n) => { await page.evaluate((P) => { document.querySelectorAll(`${P} *`).forEach(el => { const cs = getComputedStyle(el); if (cs.overflowY === "auto" || cs.overflowY === "scroll") { el.style.overflow = "visible"; el.style.maxHeight = "none"; } }); }, P); await panel().screenshot({ path: `${OUT}/${n}.png` }).catch(e => console.log("[miss]", n, e.message.slice(0, 60))); };
await page.getByRole("button", { name: "Data", exact: true }).first().click(); await page.waitForTimeout(600);
await page.getByRole("button", { name: /add table/i }).first().click(); await page.waitForTimeout(900);
console.log("table creator:", JSON.stringify(await M(`${P}, ${P} .creator-methods, ${P} .creator-method, ${P} .creator-footer, ${P} .creator-footer .control-button, ${P} .react-aria-Input`, 12), null, 1));
await shot("cr-table-empty");
await panel().locator(".creator-method").nth(1).click(); await page.waitForTimeout(500);
console.log("presets:", JSON.stringify(await M(`${P} .creator-preset-section .section-header, ${P} .list-subgroup-header, ${P} .list-subgroup-count, ${P} .preset-card, ${P} .preset-card .list-item-icon, ${P} .preset-card .list-item-name, ${P} .preset-card .list-item-desc, ${P} .preset-card .list-item-meta`, 10), null, 1));
await shot("cr-table-preset");
await panel().locator(".creator-method").nth(3).click(); await page.waitForTimeout(500);
console.log("file:", JSON.stringify(await M(`${P} .creator-dropzone, ${P} input[type=file], ${P} .creator-file-row`, 6), null, 1));
await panel().locator('input[type=file]').setInputFiles({ name: "orders-2026.csv", mimeType: "text/csv", buffer: Buffer.from("id,name,qty\n1,a,2\n2,b,3\n3,c,4\n") }); await page.waitForTimeout(600);
console.log("file row:", JSON.stringify(await M(`${P} .creator-file-row, ${P} .creator-file-row__meta, ${P} .creator-file-row__clear, ${P} .react-aria-Input`, 6)));
await shot("cr-table-file");
console.log("row box:", JSON.stringify(await panel().locator(".creator-file-row").boundingBox()), "dropzone box:", JSON.stringify(await panel().locator(".creator-dropzone").boundingBox()), "body scroll:", await page.evaluate((P) => { const b = document.querySelector(`${P} .datatable-creator-body`); return b ? `${b.scrollTop}/${b.scrollHeight}/${b.clientHeight}` : null; }, P));
await panel().locator(".creator-file-row").screenshot({ path: "/tmp/claude-501/cp2/cr-file-row.png" }).catch(e => console.log("rowshot", e.message.slice(0, 80)));
await panel().getByRole("button", { name: /^create$/i }).last().click(); await page.waitForTimeout(1500);
console.log("after create rows:", await page.evaluate(() => { const c = window.__composition_STORE__?.getState?.(); return document.querySelector('[data-panel-id="datatableEditor"] .panel-title')?.textContent; }));
await page.getByRole("button", { name: /add table/i }).first().click(); await page.waitForTimeout(900);
await panel().locator(".creator-method").nth(2).click(); await page.waitForTimeout(400); await shot("cr-table-paste");
await panel().getByRole("button", { name: /cancel/i }).last().click().catch(() => {}); await page.waitForTimeout(400);
await page.locator('[data-panel-id="datatable"]').locator(".panel-tab").nth(1).click(); await page.waitForTimeout(400);
await page.getByRole("button", { name: /add api|add endpoint/i }).first().click(); await page.waitForTimeout(900);
console.log("api creator:", JSON.stringify(await M(`${P} .section-content > *, ${P} .fieldset-legend, ${P} .react-aria-Input, ${P} .react-aria-Select, ${P} .creator-footer`, 14), null, 1));
await shot("cr-api");
await panel().getByRole("button", { name: /cancel/i }).last().click().catch(() => {}); await page.waitForTimeout(400);
await page.locator('[data-panel-id="datatable"]').locator(".panel-tab").nth(2).click(); await page.waitForTimeout(400);
await page.getByRole("button", { name: /add variable/i }).first().click(); await page.waitForTimeout(900);
console.log("var creator:", JSON.stringify(await M(`${P} .section-content > *, ${P} .fieldset-legend, ${P} .react-aria-Input, ${P} .react-aria-Select, ${P} .creator-footer`, 14), null, 1));
await shot("cr-var");
console.log("errors", errors.slice(0, 3));
await browser.close();
