import { chromium } from "playwright";
import { resolve } from "node:path";
const OUT = "/private/tmp/claude-501/-Users-admin-work-composition/f6bcc488-f176-4644-8364-3625704b801c/scratchpad/audit";
const READY = () => Boolean(window.__composition_STORE__ && window.__composition_STORE__.getState().currentPageId && document.querySelector(".app:not(.builder-booting)") && document.querySelector('[data-testid="skia-canvas-unified"]'));
const browser = await chromium.launch({ headless: false });
const page = await (await browser.newContext({ storageState: resolve("apps/builder/scripts/.auth-session.json"), viewport: { width: 1600, height: 1200 }, deviceScaleFactor: 2 })).newPage();
await page.goto("http://localhost:5173/dashboard", { waitUntil: "networkidle" });
const b = page.locator("button.dashboard-create-button").first(); await b.waitFor({ state: "visible", timeout: 15000 }); await b.click();
const i = page.locator("#new-project-name"); await i.waitFor({ state: "visible" }); await i.fill(`ey-${Date.now()}`); await i.press("Enter");
await page.waitForURL(/\/builder\/[^/?]+$/, { timeout: 60000 }); await page.waitForFunction(READY, undefined, { timeout: 90000 }); await page.waitForTimeout(1200);
const panel = async (name) => { await page.getByRole("button", { name, exact: true }).first().click(); await page.waitForTimeout(400); };
await panel("Components"); await page.locator("button.list-item").filter({ has: page.locator(".list-item-name", { hasText: /^frame$/i }) }).first().click(); await page.waitForTimeout(900); await panel("Components").catch(() => {});
await page.evaluate(() => { const s = window.__composition_STORE__.getState(); const el = s.elements.filter((e) => e.page_id === s.currentPageId && e.type === "frame").pop(); s.setSelectedElement(el.id, el.props); }); await page.waitForTimeout(400);
await panel("Styles"); const PS = '[data-panel-id="styles"]';
await page.locator(".styles-panel-tab").nth(1).click(); await page.waitForTimeout(300);
await page.locator(`${PS} .section[data-section-id="fill"] .section-actions button[aria-label="Add fill"]`).click(); await page.waitForTimeout(400);
await page.locator(`${PS} .section[data-section-id="fill"] .section-actions button[aria-label="Add fill"]`).click(); await page.waitForTimeout(400);
const eyes = () => page.evaluate((PS) => Array.from(document.querySelectorAll(`${PS} .fill-layer-row__visibility`)).map((b) => { const cs = getComputedStyle(b); const r = b.getBoundingClientRect(); return `${b.dataset.selected ? "on" : "off"} ${Math.round(r.width)}×${Math.round(r.height)} bg=${cs.backgroundColor} color=${cs.color} icon=${b.querySelector("svg")?.getAttribute("class")}`; }), PS);
console.log("eyes:", await eyes());
await page.locator(`${PS} .fill-layer-row__visibility`).first().click(); await page.waitForTimeout(400);
console.log("after toggle first:", await eyes());
console.log("row geometry:", await page.evaluate((PS) => Array.from(document.querySelectorAll(`${PS} .fill-layer-row`)).map((r) => { const g = (sel) => { const el = r.querySelector(sel); if (!el) return "-"; const b = el.getBoundingClientRect(); return `${Math.round(b.width)}×${Math.round(b.height)}`; }; return `body ${g(".fill-layer-row__body")} swatch ${g(".react-aria-ColorSwatch, .fill-layer-row__gradient-swatch")} trigger ${g(".fill-layer-row__trigger")} scrub ${g(".fill-layer-row__opacity-scrub")} actions ${g(".fill-layer-row__actions")} delete ${g(".fill-layer-row__delete")} eye ${g(".fill-layer-row__visibility")} row ${Math.round(r.getBoundingClientRect().width)}×${Math.round(r.getBoundingClientRect().height)}`; }), PS));
await page.locator(`${PS} .section[data-section-id="fill"]`).screenshot({ path: `${OUT}/eye.png` });
// 제거 버튼 실제 동작 · 팝오버 trigger 동작
await page.locator(`${PS} .fill-layer-row__delete`).last().click(); await page.waitForTimeout(400);
console.log("after delete last:", await page.evaluate(() => { const s = window.__composition_STORE__.getState(); const el = s.elements.find((e) => e.id === s.selectedElementId); return el.fills.length; }));
await page.locator(`${PS} .fill-layer-row__trigger`).first().click(); await page.waitForTimeout(500);
console.log("popover open:", await page.locator(".fill-detail-popover").count());
await page.keyboard.press("Escape"); await page.waitForTimeout(300);
for (const c of await page.locator(`${PS} .section-caret[aria-expanded="false"]`).all()) { await c.click().catch(() => {}); await page.waitForTimeout(150); }
await page.locator(`${PS} .section[data-section-id="effect"] button[aria-label="Add blur filter"]`).click(); await page.waitForTimeout(500);
await page.locator(`${PS} .section[data-section-id="effect"] button[aria-label="Box shadow actions"]`).click(); await page.waitForTimeout(400);
await page.locator('.property-row-menu-popover [role="menuitem"]').first().click(); await page.waitForTimeout(600);
console.log("shadow rows:", await page.evaluate((PS) => Array.from(document.querySelectorAll(`${PS} .section[data-section-id="effect"] .effect-layer-row`)).map((r) => { const g = (sel) => { const el = r.querySelector(sel); if (!el) return "-"; const b = el.getBoundingClientRect(); return `${Math.round(b.width)}×${Math.round(b.height)}`; }; return `row ${Math.round(r.getBoundingClientRect().width)}×${Math.round(r.getBoundingClientRect().height)} body ${g(".effect-layer-row__trigger, .effect-layer-row__body")} swatch ${g(".react-aria-ColorSwatch")} actions ${g(".effect-layer-row__actions")} remove ${g(".effect-layer-row__remove")} inset ${g(".effect-layer-row__inset")} text=「${r.querySelector(".effect-layer-row__value")?.textContent.trim()}」 tag=${r.querySelector(".effect-layer-row__tag")?.textContent}`; }), PS));
await page.locator(`${PS} .section[data-section-id="effect"]`).screenshot({ path: `${OUT}/effect-rows-before.png` });
await page.locator(`${PS} .section[data-section-id="effect"] .effect-layer-row__inset`).first().click(); await page.waitForTimeout(500);
console.log("after inset toggle:", await page.evaluate(() => { const s = window.__composition_STORE__.getState(); const el = s.elements.find((e) => e.id === s.selectedElementId); return el.props.style.boxShadow; }), await page.evaluate((PS) => document.querySelector(`${PS} .effect-layer-row__inset`)?.getAttribute("aria-label"), PS));
await page.locator(`${PS} .section[data-section-id="effect"] .effect-layer-row__remove`).first().click(); await page.waitForTimeout(500);
console.log("after remove shadow:", await page.evaluate(() => { const s = window.__composition_STORE__.getState(); const el = s.elements.find((e) => e.id === s.selectedElementId); return el.props.style.boxShadow ?? "(none)"; }));
console.log("effect rows:", await page.evaluate((PS) => Array.from(document.querySelectorAll(`${PS} .section[data-section-id="effect"] .effect-layer-row`)).map((r) => { const g = (sel) => { const el = r.querySelector(sel); if (!el) return "-"; const b = el.getBoundingClientRect(); return `${Math.round(b.width)}×${Math.round(b.height)}`; }; return `body ${g(".effect-layer-row__body, .effect-layer-row__trigger")} scrub ${g(".effect-layer-row__scrub")} action ${g(".fieldset-actions button")}`; }), PS));
await page.locator(`${PS} .section[data-section-id="effect"]`).screenshot({ path: `${OUT}/effect-rows.png` });
await browser.close();
