import { chromium } from "playwright";
import { resolve } from "node:path";
const READY = () => Boolean(window.__composition_STORE__ && window.__composition_STORE__.getState().currentPageId && document.querySelector(".app:not(.builder-booting)") && document.querySelector('[data-testid="skia-canvas-unified"]'));
const browser = await chromium.launch({ headless: false });
const page = await (await browser.newContext({ storageState: resolve("apps/builder/scripts/.auth-session.json"), viewport: { width: 1600, height: 1200 } })).newPage();
await page.goto("http://localhost:5173/dashboard", { waitUntil: "networkidle" });
const b = page.locator("button.dashboard-create-button").first(); await b.waitFor({ state: "visible", timeout: 15000 }); await b.click();
const i = page.locator("#new-project-name"); await i.waitFor({ state: "visible" }); await i.fill(`pr-${Date.now()}`); await i.press("Enter");
await page.waitForURL(/\/builder\/[^/?]+$/, { timeout: 60000 }); await page.waitForFunction(READY, undefined, { timeout: 90000 }); await page.waitForTimeout(1200);
const add = async (re) => { await page.getByRole("button", { name: "Components", exact: true }).first().click(); await page.waitForTimeout(500); const item = page.locator("button.list-item").filter({ has: page.locator(".list-item-name", { hasText: re }) }).first(); await item.scrollIntoViewIfNeeded(); await item.click(); await page.waitForTimeout(1500); await page.getByRole("button", { name: "Components", exact: true }).first().click().catch(() => {}); await page.waitForTimeout(300); };
await add(/^frame$/i);
const frameId = await page.evaluate(async () => { const st = window.__composition_STORE__.getState(); const el = st.elements.filter((e) => e.page_id === st.currentPageId && e.type === "frame").pop(); st.setSelectedElement(el.id, el.props); await new Promise((r) => setTimeout(r, 300)); window.__composition_STORE__.getState().updateSelectedStyles({ display: "flex", flexDirection: "row", width: "400px", height: "160px", gap: "12px" }); return el.id; });
await add(/^button$/i);
const btnId = await page.evaluate(() => { const st = window.__composition_STORE__.getState(); return st.elements.filter((e) => e.page_id === st.currentPageId && e.type === "Button").pop().id; });
await page.evaluate(async (id) => { const st = window.__composition_STORE__.getState(); const el = st.elements.find((e) => e.id === id); st.setSelectedElement(el.id, el.props); }, frameId); await page.waitForTimeout(500);
await page.getByRole("button", { name: "Styles", exact: true }).first().click(); await page.waitForTimeout(500);
await page.locator(".styles-panel-tab").nth(0).click(); await page.waitForTimeout(400);
const P = '[data-panel-id="styles"]';
const style = (id, keys) => page.evaluate(({ id, keys }) => { const s = window.__composition_STORE__.getState().elements.find((e) => e.id === id).props.style ?? {}; return Object.fromEntries(keys.map((k) => [k, s[k]])); }, { id, keys });
const active = () => page.evaluate(() => { const a = document.activeElement; return `${a?.tagName}.${a?.className?.split(" ")[0]} aria=${a?.getAttribute("aria-label")}`; });
console.log("gap before", await style(frameId, ["gap","rowGap","columnGap"]));
await page.locator(`${P} .displayGap .property-unit-input__suffix--trigger`).click(); await page.waitForTimeout(400);
await page.locator('.react-aria-Popover [role="option"]').filter({ hasText: /^px$/ }).click(); await page.waitForTimeout(500);
console.log("gap after reset", await style(frameId, ["gap","rowGap","columnGap"]), "active", await active(), "input", await page.locator(`${P} .displayGap input`).inputValue());
await page.locator(`${P} .section[data-section-id="layout"] .section-title`).click(); await page.waitForTimeout(300); await page.locator(`${P} .section[data-section-id="layout"] .section-title`).click(); await page.waitForTimeout(300);
console.log("gap after blur", await style(frameId, ["gap","rowGap","columnGap"]));
// button fill
await page.evaluate(async (id) => { const st = window.__composition_STORE__.getState(); const el = st.elements.find((e) => e.id === id); st.setSelectedElement(el.id, el.props); }, btnId); await page.waitForTimeout(600);
await page.locator(`${P} .section[data-section-id="transform"] .width .property-unit-input__suffix--trigger`).click(); await page.waitForTimeout(400);
await page.locator('.react-aria-Popover [role="option"]').filter({ hasText: /^fill$/ }).click(); await page.waitForTimeout(600);
console.log("after fill", await style(btnId, ["width","flexGrow"]), "active", await active(), "input", await page.locator(`${P} .width input`).inputValue());
await page.locator(`${P} .section[data-section-id="transform"] .section-title`).click(); await page.waitForTimeout(500);
console.log("after blur (section toggle)", await style(btnId, ["width","flexGrow"]));
await page.locator(`${P} .section[data-section-id="transform"] .section-title`).click(); await page.waitForTimeout(500);
console.log("field", await page.locator(`${P} .width input`).inputValue(), await page.locator(`${P} .width input`).getAttribute("placeholder"));
console.log("btn minWidth", await style(btnId, ["minWidth","minHeight","width","height"]));
await page.locator(`${P} .section[data-section-id="transform"] .aspect-ratio-select .react-aria-Button`).click(); await page.waitForTimeout(400);
await page.locator('.react-aria-Popover [role="option"]').filter({ hasText: /16:9/ }).click(); await page.waitForTimeout(500);
console.log("btn after ratio", await style(btnId, ["minWidth","minHeight","width","height","aspectRatio"]), "minW input", await page.locator(`${P} .min-width input`).inputValue(), await page.locator(`${P} .min-width input`).getAttribute("placeholder"));
await browser.close();
