import { chromium } from "playwright";
import { resolve } from "node:path";
import { writeFileSync } from "node:fs";
const BASE_URL = "http://localhost:5173";
const OUT = process.env.OUT;
const READY = () => Boolean(window.__composition_STORE__ && window.__composition_STORE__.getState().currentPageId && document.querySelector(".app:not(.builder-booting)") && document.querySelector('[data-testid="skia-canvas-unified"]'));
const browser = await chromium.launch({ headless: false });
const ctx = await browser.newContext({ storageState: resolve("apps/builder/scripts/.auth-session.json"), viewport: { width: 1600, height: 1000 }, deviceScaleFactor: 2 });
const page = await ctx.newPage();
page.on("pageerror", (e) => console.error("[page error]", e.message));
await page.goto(`${BASE_URL}/dashboard`, { waitUntil: "networkidle" });
const btn = page.locator("button.dashboard-create-button").first();
await btn.waitFor({ state: "visible", timeout: 15_000 });
await btn.click();
const input = page.locator("#new-project-name");
await input.waitFor({ state: "visible", timeout: 10_000 });
await input.fill(`panel-ui-cap-${Date.now()}`);
await input.press("Enter");
await page.waitForURL(/\/builder\/[^/?]+$/, { timeout: 60_000 });
await page.waitForFunction(READY, undefined, { timeout: 90_000 });
await page.waitForTimeout(1500);
console.log("[boot]", page.url());
const info = await page.evaluate(() => {
  const st = window.__composition_STORE__.getState();
  return { keys: Object.keys(st).filter(k => /panel|Panel|theme|Theme|select/i.test(k)), rail: [...document.querySelectorAll("button[aria-label]")].map(b => b.getAttribute("aria-label")).slice(0, 80), panels: [...document.querySelectorAll("[data-panel-id]")].map(p => p.getAttribute("data-panel-id")) };
});
console.log(JSON.stringify(info, null, 1));
await page.screenshot({ path: `${OUT}/00-boot.png` });
await browser.close();
