import { chromium } from "playwright";
import { resolve } from "node:path";
const OUT = "/private/tmp/claude-501/-Users-admin-work-composition/f6bcc488-f176-4644-8364-3625704b801c/scratchpad/audit";
const READY = () => Boolean(window.__composition_STORE__ && window.__composition_STORE__.getState().currentPageId && document.querySelector(".app:not(.builder-booting)") && document.querySelector('[data-testid="skia-canvas-unified"]'));
const browser = await chromium.launch({ headless: false });
const page = await (await browser.newContext({ storageState: resolve("apps/builder/scripts/.auth-session.json"), viewport: { width: 1600, height: 1400 }, deviceScaleFactor: 2 })).newPage();
const errors = []; page.on("pageerror", (e) => errors.push(e.message));
await page.goto("http://localhost:5173/dashboard", { waitUntil: "networkidle" });
const b = page.locator("button.dashboard-create-button").first(); await b.waitFor({ state: "visible", timeout: 15000 }); await b.click();
const i = page.locator("#new-project-name"); await i.waitFor({ state: "visible" }); await i.fill(`pp-${Date.now()}`); await i.press("Enter");
await page.waitForURL(/\/builder\/[^/?]+$/, { timeout: 60000 }); await page.waitForFunction(READY, undefined, { timeout: 90000 }); await page.waitForTimeout(1200);
const panel = async (name) => { await page.getByRole("button", { name, exact: true }).first().click(); await page.waitForTimeout(500); };
const add = async (re) => { await panel("Components"); const item = page.locator("button.list-item").filter({ has: page.locator(".list-item-name", { hasText: re }) }).first(); await item.scrollIntoViewIfNeeded(); await item.click(); await page.waitForTimeout(1500); await panel("Components"); };
const type = process.argv[2] || "button"; const storeType = process.argv[3] || type;
await add(new RegExp(`^${type}$`, "i"));
await page.evaluate(async (t) => { const st = window.__composition_STORE__.getState(); const el = st.elements.filter((e) => e.page_id === st.currentPageId && e.type.toLowerCase() === t.toLowerCase().replace(/ /g, "")).pop(); st.setSelectedElement(el.id, el.props); }, storeType); await page.waitForTimeout(500);
await panel("Properties");
const P = '[data-panel-id="properties"]';
const dump = () => page.evaluate((P) => Array.from(document.querySelectorAll(`${P} .section`)).map((s) => ({ id: s.dataset.sectionId, title: s.querySelector(".section-title")?.textContent.trim(), rows: Array.from(s.querySelectorAll(".section-content > *")).map((r) => { const rr = r.getBoundingClientRect(); const fs = r.matches("fieldset") ? [r] : Array.from(r.querySelectorAll("fieldset.properties-aria")); return `${r.className.split(" ").slice(0, 2).join(".")} ${Math.round(rr.width)}×${Math.round(rr.height)} :: ` + fs.map((f) => { const fr = f.getBoundingClientRect(); const ctl = f.querySelector(".react-aria-Group, .react-aria-control"); const cr = ctl?.getBoundingClientRect(); const btns = Array.from(f.querySelectorAll("button, [role=radio]")).map((x) => `${(x.textContent || x.getAttribute("aria-label") || "").trim().slice(0, 12)}:${Math.round(x.getBoundingClientRect().width)}×${Math.round(x.getBoundingClientRect().height)}`); return `[${f.getAttribute("aria-label") ?? f.querySelector("legend")?.textContent} ${Math.round(fr.width)}×${Math.round(fr.height)} ctl ${cr ? Math.round(cr.width) + "×" + Math.round(cr.height) : "-"} mode=${f.dataset.labelMode ?? "-"} ${btns.join(" ")}]`; }).join(" "); }) })), P);
console.log(JSON.stringify(await dump(), null, 1));
await page.evaluate((P) => { document.querySelectorAll(`${P} .section-caret[aria-expanded="false"]`).forEach((c) => c.click()); }, P); await page.waitForTimeout(300);
for (const id of ["appearance", "state", "content"]) { const sec = page.locator(`${P} .section`).filter({ has: page.locator(".section-title", { hasText: new RegExp(`^${id}$`, "i") }) }).first(); if (await sec.count()) { await sec.scrollIntoViewIfNeeded(); await sec.screenshot({ path: `${OUT}/props-${type}-${id}.png` }); } }
console.log("errors", errors.slice(0, 3));
await browser.close();
