import { chromium } from "playwright";
import { resolve } from "node:path";
const READY = () => Boolean(window.__composition_STORE__ && window.__composition_STORE__.getState().currentPageId && document.querySelector(".app:not(.builder-booting)") && document.querySelector('[data-testid="skia-canvas-unified"]'));
const browser = await chromium.launch({ headless: false });
const page = await (await browser.newContext({ storageState: resolve("apps/builder/scripts/.auth-session.json"), viewport: { width: 1600, height: 1100 }, deviceScaleFactor: 2 })).newPage();
await page.goto("http://localhost:5173/dashboard", { waitUntil: "networkidle" });
const b = page.locator("button.dashboard-create-button").first(); await b.waitFor({ state: "visible", timeout: 15000 }); await b.click();
const i = page.locator("#new-project-name"); await i.waitFor({ state: "visible" }); await i.fill(`ps-${Date.now()}`); await i.press("Enter");
await page.waitForURL(/\/builder\/[^/?]+$/, { timeout: 60000 }); await page.waitForFunction(READY, undefined, { timeout: 90000 }); await page.waitForTimeout(1200);
await page.evaluate(async () => { const st = window.__composition_STORE__.getState(); const body = st.elements.find((e) => e.type === "body" && e.page_id === st.currentPageId) ?? st.elements.find((e) => e.type === "body"); const now = new Date().toISOString(); const id = crypto.randomUUID(); await st.addElement({ id, type: "Button", parent_id: body.id, page_id: body.page_id, order_num: 1, created_at: now, updated_at: now, props: { style: {}, children: "Hi" } }); await new Promise((r) => setTimeout(r, 500)); const s2 = window.__composition_STORE__.getState(); s2.setSelectedElement(id, s2.elements.find((e) => e.id === id)?.props); });
await page.waitForTimeout(700);
await page.getByRole("button", { name: "Properties", exact: true }).first().click().catch(() => {}); await page.waitForTimeout(500);
const sel = page.locator('[data-panel-id="properties"] .react-aria-Select .react-aria-Button').first();
console.log("trigger", await sel.getAttribute("aria-label"), await sel.textContent());
await sel.click(); await page.waitForTimeout(400);
console.log(JSON.stringify(await page.evaluate(() => Array.from(document.querySelectorAll(".property-select-popover .react-aria-ListBoxItem")).slice(0, 4).map((el) => { const r = el.getBoundingClientRect(); const cs = getComputedStyle(el); return `${el.textContent} ${Math.round(r.width)}×${Math.round(r.height)} fs${cs.fontSize} lh${cs.lineHeight} pad${cs.padding}`; }))));
await browser.close();
