import { chromium } from "playwright";
import { resolve } from "node:path";
import { mkdirSync } from "node:fs";
const OUT = "/private/tmp/claude-501/-Users-admin-work-composition/f6bcc488-f176-4644-8364-3625704b801c/scratchpad/props-after"; mkdirSync(OUT, { recursive: true });
const READY = () => Boolean(window.__composition_STORE__ && window.__composition_STORE__.getState().currentPageId && document.querySelector(".app:not(.builder-booting)") && document.querySelector('[data-testid="skia-canvas-unified"]'));
const browser = await chromium.launch({ headless: false });
const page = await (await browser.newContext({ storageState: resolve("apps/builder/scripts/.auth-session.json"), viewport: { width: 1600, height: 3000 }, deviceScaleFactor: 1 })).newPage();
const errors = []; page.on("pageerror", (e) => errors.push(e.message));
await page.goto("http://localhost:5173/dashboard", { waitUntil: "networkidle" });
const b = page.locator("button.dashboard-create-button").first(); await b.waitFor({ state: "visible", timeout: 15000 }); await b.click();
const i = page.locator("#new-project-name"); await i.waitFor({ state: "visible" }); await i.fill(`st-${Date.now()}`); await i.press("Enter");
await page.waitForURL(/\/builder\/[^/?]+$/, { timeout: 60000 }); await page.waitForFunction(READY, undefined, { timeout: 90000 }); await page.waitForTimeout(1200);
const panel = async (name) => { await page.getByRole("button", { name, exact: true }).first().click(); await page.waitForTimeout(400); };
const P = '[data-panel-id="properties"]';
await panel("Components");
const item = page.locator("button.list-item").filter({ has: page.locator(".list-item-name", { hasText: /^tabs$/i }) }).first();
await item.scrollIntoViewIfNeeded(); await item.click(); await page.waitForTimeout(900);
await panel("Components").catch(() => {});
await panel("Properties"); await page.waitForTimeout(400);
const S = `${P} [data-state-owner]`;
// 암묵 상태 이름 짓기
const inp = page.locator(`${S} .state-def-name-input`).first();
console.log("unnamed row:", await page.evaluate((S) => { const r = document.querySelector(`${S} .state-def--unnamed .list-row`); const g = r.querySelector(".list-row__actions").getBoundingClientRect(); const inp = r.querySelector("input").getBoundingClientRect(); return `actions ${Math.round(g.width)}×${Math.round(g.height)} input ${Math.round(inp.width)}×${Math.round(inp.height)}`; }, S));
await page.locator(`${P} .panel-contents`).screenshot({ path: `${OUT}/state-unnamed.png` });
await inp.fill("tab"); await inp.press("Enter"); await page.waitForTimeout(500);
// 명시 상태 추가 + 펼치기
await page.locator(`${S} [data-group="explicit"] .control-button`).click(); await page.waitForTimeout(500);
const rows = await page.evaluate((S) => Array.from(document.querySelectorAll(`${S} .state-def`)).map((d) => { const body = d.querySelector(".list-row__body")?.getBoundingClientRect(); const acts = d.querySelector(".list-row__actions")?.getBoundingClientRect(); const btns = Array.from(d.querySelectorAll(".list-row__action")).map((x) => `${Math.round(x.getBoundingClientRect().width)}×${Math.round(x.getBoundingClientRect().height)}`); return `${d.querySelector(".state-def-name")?.textContent} [${d.querySelector(".state-def-meta")?.textContent}|${d.querySelector(".state-def-usage")?.textContent}] body ${Math.round(body?.width)}×${Math.round(body?.height)} acts ${acts ? Math.round(acts.width) + "×" + Math.round(acts.height) : "-"} btn ${btns.join(",")}`; }), S);
console.log("rows:", rows.join(" | "));
const toggles = page.locator(`${S} [data-group="implicit"] .state-def-toggle`);
await toggles.first().click(); await page.waitForTimeout(300);
console.log("editor:", await page.evaluate((S) => Array.from(document.querySelectorAll(`${S} .state-def-editor fieldset`)).map((f) => `${f.querySelector("legend")?.textContent} ${Math.round(f.getBoundingClientRect().width)}×${Math.round(f.getBoundingClientRect().height)}`).join(" | "), S));
console.log("legends:", await page.evaluate((S) => Array.from(document.querySelectorAll(`${S} fieldset.state-group > legend`)).map((l) => l.textContent.trim()).join(" / "), S));
await page.evaluate((P) => { const pc = document.querySelector(`${P} .panel-contents`); const h = pc.scrollHeight + 8; let el = pc; while (el && !el.classList.contains("panel-dock-surface")) { el.style.setProperty("height", el === pc ? h + "px" : "auto", "important"); el.style.setProperty("max-height", "none", "important"); el.style.setProperty("overflow", "visible", "important"); el = el.parentElement; } }, P); await page.waitForTimeout(200);
await page.locator(`${P} .panel-contents`).screenshot({ path: `${OUT}/state-tabs.png` });
console.log("errors", errors.slice(0, 5));
await browser.close();
