import { chromium } from "playwright";
import { resolve } from "node:path";
const READY = () => Boolean(window.__composition_STORE__ && window.__composition_STORE__.getState().currentPageId && document.querySelector(".app:not(.builder-booting)") && document.querySelector('[data-testid="skia-canvas-unified"]'));
const browser = await chromium.launch({ headless: false });
const page = await (await browser.newContext({ storageState: resolve("apps/builder/scripts/.auth-session.json"), viewport: { width: 1600, height: 1000 }, deviceScaleFactor: 2 })).newPage();
await page.goto("http://localhost:5173/dashboard", { waitUntil: "networkidle" });
const b = page.locator("button.dashboard-create-button").first(); await b.waitFor({ state: "visible", timeout: 15000 }); await b.click();
const i = page.locator("#new-project-name"); await i.waitFor({ state: "visible" }); await i.fill(`tip-${Date.now()}`); await i.press("Enter");
await page.waitForURL(/\/builder\/[^/?]+$/, { timeout: 60000 }); await page.waitForFunction(READY, undefined, { timeout: 90000 }); await page.waitForTimeout(1200);
await page.evaluate(async () => { const st = window.__composition_STORE__.getState(); const body = st.elements.find(e => e.type === "body" && e.page_id === st.currentPageId) ?? st.elements.find(e => e.type === "body"); const now = new Date().toISOString(); const id = crypto.randomUUID(); await st.addElement({ id, type: "Button", parent_id: body.id, page_id: body.page_id, order_num: 99, created_at: now, updated_at: now, props: { children: "Primary action" } }, { skipHistory: true }); await new Promise(r => setTimeout(r, 800)); const st2 = window.__composition_STORE__.getState(); st2.setSelectedElement(id, st2.elements.find(e => e.id === id)?.props); });
await page.waitForTimeout(600);
const ab = page.locator(".contextual-action-bar-item").nth(1); const bb = await ab.boundingBox();
await page.mouse.move(bb.x + 14, bb.y + 14); await page.waitForTimeout(1500);
await page.screenshot({ path: "/tmp/claude-501/after/tip-ab.png" }); console.log("ab", JSON.stringify(bb));
const rail = page.locator(".panel-toggle-rail button").first(); const rb = await rail.boundingBox();
await page.keyboard.press("Tab"); await page.evaluate(() => document.querySelector(".panel-toggle-rail button").focus()); await page.keyboard.press("Shift"); await page.waitForTimeout(1200);
const t = await page.evaluate(() => { const d = document.createElement("div"); d.className = "action-tooltip"; d.innerHTML = '<span class="action-tooltip-label">Styles</span><kbd class="action-tooltip-kbd">⌥S</kbd>'; document.body.appendChild(d); return Array.from(document.querySelectorAll(".action-tooltip, .action-tooltip-kbd, [role=tooltip]")).map(e => { const r = e.getBoundingClientRect(); const c = getComputedStyle(e); return `${e.className} ${Math.round(r.width)}×${Math.round(r.height)} pad${c.padding} r${c.borderRadius} fs${c.fontSize} gap${c.gap}`; }); });
console.log(JSON.stringify(t));
await page.screenshot({ path: "/tmp/claude-501/after/tip-rail.png" }); console.log("rail", JSON.stringify(rb));
await browser.close();
