/**
 * @fileoverview Canonical Component Vocabulary — ADR-903 P0
 *
 * **scope 분리 (R5)**: 본 파일의 `ComponentTag`는 오직 `Element.type` /
 * `CanonicalNode.type`의 값 공간이다. `DataBinding.type` ("collection" | "value"
 * | "field") 및 `FieldDefinition.type` (FieldType 7-literal)과는 **객체 경로가
 * 다른 별개 필드**이며 값 공간 교집합 0건 — compile-time disjoint 보장.
 */

/**
 * Canonical Component Tag — composition 컴포넌트 vocabulary.
 *
 * 값 공간 정책 (ADR-903 §type vocabulary policy):
 * - **허용**: composition Component 114개 + pencil 공용 구조 타입 3개 (`ref` | `frame` | `group`) = 117 literal
 * - **제외**: pencil primitive 10종 (`rectangle` / `ellipse` / `line` / `polygon` / `path` /
 *   `text` / `note` / `prompt` / `context` / `icon_font`) — import/export adapter 경유만 등장
 *
 * 실측: 본 `ComponentTag` union 멤버 114 component + 구조 타입 3개 = 117 (Autocomplete 폐기 2026-06-09 / DateSegment+TimeSegment 폐기 2026-06-09 / Accordion 폐기 2026-06-10 — DisclosureGroup 중복 / MaskedFrame 폐기 2026-06-16 — dead orphan, factory 0건, ADR-912 step 4). 주의: `*.spec.ts` 파일 수와는 별개 — properties-only / child sub-part spec 은 union 비멤버. TimeSegment 는 vocab union 비멤버였던 undeclared alias (tagToElement 동시 청산).
 */
export type ComponentTag =
  // ── composition Component Tags (114개, 알파벳 순) ──
  | "Avatar"
  | "AvatarGroup"
  | "Badge"
  | "Body"
  | "Breadcrumb"
  | "Breadcrumbs"
  | "Button"
  | "ButtonGroup"
  | "Calendar"
  | "CalendarGrid"
  | "CalendarHeader"
  | "Card"
  | "CardContent"
  | "CardFooter"
  | "CardHeader"
  // ADR-148 Phase 4 정정: 실존 컴포넌트(catalog rule + renderer + Card origin 자식)인데
  //   유니온에서 누락 — cardTemplateOrigins(Phase 3) 가 canonical 자식 type 으로 사용.
  | "CardPreview"
  | "CardView"
  | "Chart"
  | "Checkbox"
  | "CheckboxGroup"
  | "CheckboxIndicator"
  | "CheckboxItems"
  | "Code"
  | "ColorArea"
  | "ColorField"
  | "ColorPicker"
  | "ColorSlider"
  | "ColorSwatch"
  | "ColorSwatchPicker"
  | "ColorWheel"
  | "ComboBox"
  | "DateField"
  | "DateInput"
  | "DatePicker"
  | "DateRangePicker"
  | "Description"
  | "Dialog"
  | "DialogTrigger"
  | "Disclosure"
  | "DisclosureGroup"
  | "DisclosureHeader"
  | "DropZone"
  | "Field"
  | "FieldError"
  | "FileTrigger"
  | "Form"
  | "GridList"
  | "GridListItem"
  | "Group"
  | "Header"
  | "Heading"
  | "Icon"
  | "IllustratedMessage"
  | "Image"
  | "InlineAlert"
  | "Input"
  | "Kbd"
  | "Keyboard"
  | "Label"
  | "Link"
  | "ListBox"
  | "ListBoxItem"
  | "Menu"
  | "MenuItem"
  | "Meter"
  | "MeterTrack"
  | "MeterValue"
  | "Modal"
  | "Nav"
  | "NumberField"
  | "Pagination"
  | "Paragraph"
  | "Popover"
  | "ProgressBar"
  | "ProgressBarFill"
  | "ProgressBarTrack"
  | "ProgressBarValue"
  | "ProgressCircle"
  | "Radio"
  | "RadioGroup"
  | "RadioIndicator"
  | "RadioItems"
  | "RangeCalendar"
  | "SearchField"
  | "Section"
  | "Select"
  | "SelectIcon"
  | "SelectValue"
  | "Separator"
  | "Skeleton"
  | "SubmenuTrigger"
  | "Autocomplete"
  | "Slider"
  | "SliderOutput"
  | "SliderThumb"
  | "SliderTrack"
  | "Slot"
  | "StatusLight"
  | "Switch"
  | "SwitchIndicator"
  | "Tab"
  | "Table"
  | "TableView"
  | "TabList"
  | "TabPanel"
  | "TabPanels"
  | "Tabs"
  | "Tag"
  | "TagGroup"
  | "TagList"
  | "TailSwatch"
  | "Text"
  | "TextArea"
  | "TextField"
  | "TimeField"
  | "Toast"
  | "ToggleButton"
  | "ToggleButtonGroup"
  | "Toolbar"
  | "Tooltip"
  | "TooltipTrigger"
  | "Tree"
  // ── pencil 공용 구조 타입 3개 ──
  | "ref"
  | "frame"
  | "group";
