import { resolve } from "node:path";
import { chromium } from "playwright";
import { waitReady, seedDocument } from "../perf-baseline.mjs";
const browser = await chromium.launch({ headless: false });
const context = await browser.newContext({ storageState: resolve("apps/builder/scripts/.auth-session.json"), viewport: { width: 1440, height: 900 } });
const page = await context.newPage();
await page.goto("http://localhost:5173/dashboard", { waitUntil: "networkidle" });
await page.locator("button.dashboard-create-button").first().click();
const input = page.locator("#new-project-name");
await input.fill(`probe-${Date.now()}`); await input.press("Enter");
await page.waitForURL(/\/builder\/[^/?]+$/, { timeout: 90_000 });
await waitReady(page); await page.waitForTimeout(1500);
const home = await page.evaluate(() => window.__composition_STORE__.getState().currentPageId);
await page.evaluate(() => {
  const st = window.__composition_STORE__.getState();
  const body = st.elements.find((e) => e.type === "body" && e.page_id === st.currentPageId);
  const now = new Date().toISOString();
  st.addElement({ id: "probe-form", customId: "probe-form", type: "ref", ref: "component-form", componentName: "Form", parent_id: body.id, page_id: st.currentPageId, props: {}, created_at: now, updated_at: now });
});
await seedDocument(page, 600, "mixed", 1);
await page.waitForTimeout(2500);
const info = (label) => page.evaluate((label) => { const m = window.__composition_LAYOUT_DEBUG__.getSharedLayoutMap(); const ks=[...m.keys()]; return `${label}: size ${m.size} probe ${ks.filter(k=>k.startsWith("probe")).length} originForm ${ks.filter(k=>k.startsWith("component-form")).length} seed ${ks.filter(k=>k.startsWith("perf-seed")).length}`; }, label);
console.log(await info("A home"));
await page.evaluate(() => { window.__composition_APPLY_VIEWPORT__({ scale: 1, x: 100, y: 100 }); window.__composition_STORE__.getState().setSelectedElement(null); });
await page.waitForTimeout(1500);
console.log(await info("B home after viewport"));
await page.screenshot({ type: "png" });
await page.waitForTimeout(500);
console.log(await info("C home after screenshot"));
await page.evaluate(() => window.__composition_STORE__.getState().setCurrentPageId("page-components"));
await page.waitForTimeout(2500);
console.log(await info("D components"));
await page.evaluate(() => { window.__composition_APPLY_VIEWPORT__({ scale: 1, x: 100, y: -500 }); });
await page.waitForTimeout(1500);
console.log(await info("E components after viewport"));
await page.evaluate(() => { const a = window.__composition_THEME_ACTIONS__; a.addThemeFromActive(); a.setActiveTheme(a.readThemesCollection().order[1]); a.setActiveThemePreset({ tint: "red" }); });
await page.waitForTimeout(2500);
console.log(await info("F components after theme"));
await page.evaluate(() => { window.__composition_APPLY_VIEWPORT__({ scale: 1, x: 100, y: -300 }); });
await page.waitForTimeout(1500);
console.log(await info("G components after theme+viewport"));
await page.evaluate((home) => window.__composition_STORE__.getState().setCurrentPageId(home), home);
await page.waitForTimeout(3000);
console.log(await info("H home again"));
await page.evaluate(() => { window.__composition_APPLY_VIEWPORT__({ scale: 1, x: 100, y: 100 }); });
await page.waitForTimeout(3000);
console.log(await info("I home again + viewport"));
await browser.close();
