import { resolve } from "node:path";
import { chromium } from "playwright";
import { waitReady, seedDocument } from "../perf-baseline.mjs";
const browser = await chromium.launch({ headless: false });
const context = await browser.newContext({ storageState: resolve("apps/builder/scripts/.auth-session.json"), viewport: { width: 1440, height: 900 } });
const page = await context.newPage();
await page.goto("http://localhost:5173/dashboard", { waitUntil: "networkidle" });
await page.locator("button.dashboard-create-button").first().click();
const input = page.locator("#new-project-name");
await input.fill(`probe-${Date.now()}`); await input.press("Enter");
await page.waitForURL(/\/builder\/[^/?]+$/, { timeout: 90_000 });
await waitReady(page); await page.waitForTimeout(1500);
const home = await page.evaluate(() => window.__composition_STORE__.getState().currentPageId);
await page.evaluate(() => {
  const st = window.__composition_STORE__.getState();
  const body = st.elements.find((e) => e.type === "body" && e.page_id === st.currentPageId);
  const now = new Date().toISOString();
  st.addElement({ id: "probe-form", customId: "probe-form", type: "ref", ref: "component-form", componentName: "Form", parent_id: body.id, page_id: st.currentPageId, props: {}, created_at: now, updated_at: now });
});
await seedDocument(page, 600, "mixed", 1);
await page.waitForTimeout(2500);
const keys = (re) => page.evaluate((re) => [...window.__composition_LAYOUT_DEBUG__.getSharedLayoutMap().entries()].filter(([k]) => new RegExp(re).test(k)).map(([k,v]) => [k, v.x, v.y, v.width, v.height]), re);
console.log("home after seed:", await keys("probe"));
await page.evaluate(() => { const a = window.__composition_THEME_ACTIONS__; a.addThemeFromActive(); a.setActiveTheme(a.readThemesCollection().order[1]); a.setActiveThemePreset({ tint: "red" }); });
await page.waitForTimeout(2500);
console.log("home after theme switch probe:", (await keys("probe")).length, "size", await page.evaluate(() => window.__composition_LAYOUT_DEBUG__.getSharedLayoutMap().size));
await page.evaluate(() => { const a = window.__composition_THEME_ACTIONS__; a.setActiveTheme(a.readThemesCollection().order[0]); });
await page.waitForTimeout(2500);
console.log("home after 2nd theme switch probe:", (await keys("probe")).length, "size", await page.evaluate(() => window.__composition_LAYOUT_DEBUG__.getSharedLayoutMap().size));
await page.evaluate(() => window.__composition_STORE__.getState().setCurrentPageId("page-components"));
await page.waitForTimeout(2500);
console.log("components chain:", await keys("^component-form(__actions)?(/component-buttongroup__2)?$"));
console.log("components probe:", (await keys("probe")).length);
await page.evaluate((home) => window.__composition_STORE__.getState().setCurrentPageId(home), home);
await page.waitForTimeout(3000);
console.log("home again probe:", (await keys("probe")).length);
await page.evaluate(() => { const a = window.__composition_THEME_ACTIONS__; a.setActiveTheme(a.readThemesCollection().order[1]); });
await page.waitForTimeout(2500);
console.log("home again after switch probe:", (await keys("probe")).length, "accent", await keys("^perf-seed-1$"));
console.log("home again size:", await page.evaluate(() => window.__composition_LAYOUT_DEBUG__.getSharedLayoutMap().size));
await browser.close();
