/**
 * preset 문자열 카탈로그 — `presetData.*` (생성 풀) · `presetField.*` (스키마 라벨) ·
 * `presetMeta.*` (카드 설명). Add Table 은 lazy 표면이라 이 표도 initial 번들 밖에 둔다
 * (2026-09-16 — 메인 i18n 카탈로그에 실렸을 때 Builder initial 상한 +2,116 B 초과).
 *
 * 해소는 적용 시점 (`PresetTranslate`) — 굳은 뒤 사용자 데이터라 다시 번역하지 않는다.
 * locale 은 provider 의 `locale` (React) 또는 저장된 locale (`getStoredLocale`, 순수 모듈).
 */

import { getStoredLocale } from "../../../../i18n/locales";
import type { SupportedLocale } from "../../../../i18n/types";
import type { PresetTranslate } from "./types";

type PresetArgs = Record<string, string | number | boolean> | undefined;
type PresetMessage = string | ((args?: PresetArgs) => string);
type Nested = Record<string, Record<string, string>>;

const koKR: Nested = {
presetData: {
  companies:
    "테크노베이션, 디지털솔루션, 스마트시스템즈, 퓨처테크, 이노베이션랩, 클라우드웍스, 데이터인사이트, 넥스트제너레이션, 글로벌소프트, 크리에이티브스튜디오",
  jobTitles:
    "프론트엔드 개발자, 백엔드 개발자, 풀스택 개발자, 데이터 엔지니어, DevOps 엔지니어, UI/UX 디자이너, 프로젝트 매니저, 제품 관리자, QA 엔지니어, 시스템 아키텍트",
  lastNames: "김, 이, 박, 최, 정, 강, 조, 윤, 장, 임",
  firstNames: "민준, 서준, 예준, 도윤, 시우, 서연, 서윤, 지우, 하은, 수빈",
  nameOrder: "family-first",
  industries: "IT 서비스, 제조, 금융, 교육, 헬스케어, 컨설팅, 미디어",
  departments:
    "연구개발, 영업, 인사, 재무, 고객지원, 제품관리, 디자인, 품질관리",
  userStatuses: "활성, 초대중, 휴면, 중지",
  jobLevels: "주니어, 미들, 시니어, 리드, 디렉터",
  projectStatuses: "준비, 진행중, 보류, 완료",
  productCategories: "전자기기, 의류, 식품, 가구, 스포츠, 도서, 화장품",
  orderStatuses: "대기, 처리중, 배송중, 완료, 취소",
  roleNames: "관리자, 편집자, 뷰어, 게스트, 슈퍼관리자",
  roleDescriptions:
    "전체 관리 권한, 콘텐츠 편집 가능, 읽기 전용, 제한된 접근, 최고 권한",
  permissionNames:
    "사용자 보기, 사용자 관리, 프로젝트 보기, 프로젝트 편집, 설정 관리",
  permissionDescriptions:
    "사용자 목록 조회, 사용자 생성/수정/삭제, 프로젝트 조회, 프로젝트 수정, 시스템 설정 변경",
  plans: "무료, 프로, 엔터프라이즈",
  cityName: "서울시",
  districts: "강남구, 서초구, 마포구, 송파구",
  engineStatuses: "설계, 제작, 테스트, 양산, 단종",
  manufacturers: "현대모비스, LG전자, 삼성SDI, 만도, 한온시스템",
  suppliers: "현대위아, 대원강업, 세원정공, 화신, 동희오토",
  partStatuses: "정상, 단종, 검토중, 승인대기",
  auditActions: "생성, 수정, 삭제, 권한 변경, 로그인",
  departmentDescription: "{name} 부서입니다.",
  projectName: "프로젝트 {n}",
  productName: "상품 {n}",
  productDescription: "상품 {n}에 대한 설명입니다.",
  categoryDescription: "{name} 카테고리",
  shippingAddress: "{city} {district}",
  engineName: "엔진 {n}",
  partName: "부품 {n}",
  auditDescription: "작업 {n}에 대한 로그",
  personName: "{last}{first}",
  localeId: "ko",
  firstNamesMale: "민준, 서준, 예준, 도윤, 시우, 하준, 주원, 지호, 준우, 건우",
  firstNamesFemale: "서연, 서윤, 지우, 하은, 수빈, 지민, 하윤, 채원, 지아, 유나",
  streets: "테헤란로, 강남대로, 올림픽로, 세종대로, 한강대로, 마포대로, 동작대로, 양재대로",
  cities: "서울시, 부산시, 인천시, 대구시, 대전시, 광주시, 수원시, 성남시",
  regions: "서울, 경기, 부산, 인천, 대구, 대전, 광주, 강원",
  country: "대한민국",
  postcodeFormat: "#####",
  phoneFormat: "02-####-####",
  cellFormat: "010-####-####",
  timezones: "+9:00",
  words: "바다, 하늘, 나무, 구름, 강, 산, 별, 바람, 꽃, 도시, 아침, 저녁, 여행, 기록, 이야기, 시간, 공간, 빛, 소리, 길",
  productAdjectives: "프리미엄, 슬림, 클래식, 에코, 스마트, 컴팩트, 데일리, 프로",
  productMaterials: "스틸, 우드, 코튼, 가죽, 세라믹, 알루미늄, 린넨, 유리",
  productNouns: "의자, 램프, 키보드, 텀블러, 백팩, 스피커, 노트, 시계",
  brands: "모던하우스, 라이프온, 그린랩, 스튜디오K, 노바, 오리온, 제니스, 픽셀",
  availabilityStatuses: "재고 있음, 재고 부족, 품절",
  reviewComments: "기대 이상이에요!, 설명대로 잘 동작합니다., 배송이 빨랐어요., 가성비가 좋습니다., 다시 구매할 의향 있어요., 포장이 아쉬웠습니다., 색상이 사진과 조금 달라요.",
  cuisines: "한식, 일식, 중식, 이탈리안, 멕시칸, 인도, 태국, 프렌치",
  mealTypes: "아침, 점심, 저녁, 간식, 브런치",
  dishes: "비빔밥, 김치찌개, 파스타, 타코, 라멘, 커리, 불고기, 리조또, 잡채, 떡볶이",
  difficulties: "쉬움, 보통, 어려움",
  currency: "KRW",
  merchants: "카페 모카, 마트 24, 서점 페이지, 주유소 하이, 편의점 CU, 배달의집, 지하철 교통, 온라인몰 스토어",
  transactionCategories: "식비, 교통, 쇼핑, 공과금, 문화, 의료, 교육, 여행",
  transactionTypes: "출금, 입금, 환불",
  tags: "신규, 인기, 세일, 추천, 한정, 베스트",
  todoTasks: "보고서 작성, 고객 미팅 준비, PR 리뷰, 스프린트 계획, 디자인 검토, 배포 확인, 문서 갱신, 예산 정리, 인터뷰 일정 조율, 회의록 공유",
  priorities: "낮음, 보통, 높음",
  quotes: "단순함은 궁극의 정교함이다., 계속 갈망하라 여전히 우직하게., 시작이 반이다., 천 리 길도 한 걸음부터., 배움에는 끝이 없다., 오늘 할 수 있는 일을 내일로 미루지 마라., 실패는 성공의 어머니다., 아는 것이 힘이다.",
  quoteAuthors: "레오나르도 다빈치, 스티브 잡스, 아리스토텔레스, 노자, 공자, 벤저민 프랭클린, 토머스 에디슨, 프랜시스 베이컨",
  colorNames: "빨강, 파랑, 초록, 노랑, 보라, 주황, 회색, 검정",
},
presetField: {
  id: "ID",
  isActive: "활성",
  num: "번호",
  name: "이름",
  email: "이메일",
  phone: "전화번호",
  company: "회사",
  jobTitle: "직책",
  status: "상태",
  jobLevel: "직급",
  createdAt: "생성일",
  roleName: "역할명",
  description: "설명",
  scope: "범위",
  permissionList: "권한 목록",
  permissionName: "권한명",
  category: "카테고리",
  roleId: "역할 ID",
  inviterId: "초대자 ID",
  expiresAt: "만료일",
  orgName: "조직명",
  industry: "산업",
  domain: "도메인",
  plan: "플랜",
  orgId: "조직 ID",
  departmentName: "부서명",
  managerId: "매니저 ID",
  departmentId: "부서 ID",
  projectName: "프로젝트명",
  startDate: "시작일",
  endDate: "종료일",
  budget: "예산",
  client: "고객사",
  visibility: "공개범위",
  productName: "상품명",
  price: "가격",
  stock: "재고",
  image: "이미지",
  categoryName: "카테고리명",
  parentCategoryId: "상위 카테고리 ID",
  order: "순서",
  userId: "사용자 ID",
  orderItems: "주문 항목",
  total: "총액",
  shippingAddress: "배송지",
  orderedAt: "주문일",
  projectId: "프로젝트 ID",
  engineName: "엔진명",
  code: "코드",
  version: "버전",
  manufacturer: "제조사",
  specifications: "사양",
  engineId: "엔진 ID",
  parentPartId: "상위 부품 ID",
  partName: "부품명",
  partCode: "부품 코드",
  type: "유형",
  level: "레벨",
  quantity: "수량",
  unit: "단위",
  supplier: "공급사",
  cost: "비용",
  leadTime: "리드타임 (일)",
  actorId: "수행자 ID",
  entityType: "엔티티 유형",
  entityId: "엔티티 ID",
  action: "작업",
  time: "시간",
  ipAddress: "IP 주소",
  allocation: "할당량 (%)",
  billable: "청구 대상",
  joinedAt: "참여일",
  lastActive: "마지막 활동",
  title: "제목",
  body: "본문",
  tags: "태그",
  coverImage: "대표 이미지",
  likes: "좋아요",
  dislikes: "싫어요",
  views: "조회수",
  publishedAt: "게시일",
  postId: "게시글 ID",
  author: "작성자",
  task: "할 일",
  completed: "완료",
  priority: "우선순위",
  dueDate: "마감일",
  recipeName: "레시피 이름",
  cuisine: "요리 종류",
  mealType: "식사 종류",
  difficulty: "난이도",
  ingredients: "재료",
  instructions: "조리 순서",
  prepTime: "준비 시간 (분)",
  cookTime: "조리 시간 (분)",
  servings: "인분",
  calories: "칼로리 (1인분)",
  rating: "평점",
  reviewCount: "리뷰 수",
  quote: "인용문",
  brand: "브랜드",
  sku: "SKU",
  discount: "할인율 (%)",
  availability: "재고 상태",
  weight: "무게 (kg)",
  dimensions: "치수",
  thumbnail: "썸네일",
  images: "이미지 목록",
  slug: "슬러그",
  cartProducts: "장바구니 상품",
  discountedTotal: "할인 적용 총액",
  totalProducts: "상품 수",
  totalQuantity: "총 수량",
  updatedAt: "수정일",
  productId: "상품 ID",
  comment: "댓글",
  gender: "성별",
  reviewer: "리뷰어",
  reviewerEmail: "리뷰어 이메일",
  avatar: "아바타",
  verifiedPurchase: "구매 확인",
  reviewDate: "리뷰일",
  accountId: "계좌 번호",
  transactionType: "거래 유형",
  amount: "금액",
  currency: "통화",
  merchant: "가맹점",
  balance: "거래 후 잔액",
  reference: "참조 번호",
  transactedAt: "거래 일시",
  cardholder: "카드 소유자",
  cardType: "카드 종류",
  cardNumber: "카드 번호",
  cardNumberMasked: "카드 번호 (마스킹)",
  last4: "뒤 4자리",
  expiry: "만료 (MM/YY)",
  billingAddress: "청구 주소",
  isDefault: "기본 카드",
  customer: "고객",
  invoiceItems: "청구 항목",
  subtotal: "소계",
  taxRate: "세율",
  tax: "세금",
  issuedAt: "발행일",
  paidAt: "결제일",
  picsumId: "사진 ID",
  width: "너비",
  height: "높이",
  url: "URL",
  grayscale: "흑백",
  blur: "흐림",
  previewUrl: "미리보기 URL",
  color: "대표 색",
  uploadedAt: "업로드일",
  userAgent: "User Agent",
  firstName: "이름",
  lastName: "성",
  username: "사용자명",
  birthDate: "생년월일",
  age: "나이",
  cell: "휴대전화",
  street: "도로명 주소",
  city: "도시",
  region: "시/도",
  country: "국가",
  postcode: "우편번호",
  latitude: "위도",
  longitude: "경도",
  timezone: "시간대",
  registeredAt: "가입일",
  address: "주소",
  favorite: "즐겨찾기",
  notes: "메모",
  lastContactedAt: "마지막 연락",
  salary: "연봉",
  hireDate: "입사일",
  remote: "원격 근무",
},
presetMeta: {
  categoryUsersAuth: "사용자, 역할, 권한 관리",
  categoryOrganization: "조직, 부서, 프로젝트 관리",
  categoryEcommerce: "상품, 카테고리, 주문 관리",
  categoryManufacturing: "제품, 부품, BOM 관리",
  categorySystem: "시스템 로그, 멤버십 관리",
  users: "사용자 정보 관리",
  roles: "역할 및 권한 그룹 정의",
  permissions: "세부 권한 정의",
  invitations: "사용자 초대 관리",
  organizations: "조직/회사 정보",
  departments: "부서 정보",
  projects: "프로젝트 관리",
  products: "상품 정보",
  categories: "상품 카테고리",
  orders: "주문 정보",
  engines: "엔진/제품 정보",
  components: "부품 (BOM) 정보",
  auditLogs: "시스템 감사 로그",
  projectMembers: "프로젝트 멤버십 관리",
  categoryPeople: "프로필, 연락처, 직원 (randomuser 어법)",
  categoryContent: "게시글, 댓글, 할 일, 레시피, 인용문",
  categoryFinance: "거래, 결제 카드, 청구서",
  categoryMedia: "이미지 목록 (picsum 플레이스홀더)",
  profiles: "성별·이름·초상이 일치하는 전체 프로필",
  contacts: "연락처 — 회사·주소는 일부 비움",
  employees: "직원 — 직급별 연봉 구간, 상급자 참조",
  carts: "장바구니 — 합계·할인 총액 파생",
  reviews: "상품 리뷰 — 평점 분포 5점 편중",
  posts: "게시글 — 태그·반응·조회수",
  comments: "댓글 — 게시글 FK, 작성자 객체",
  todos: "할 일 — 완료 여부에 따른 마감일",
  recipes: "레시피 — 재료·조리 순서·난이도",
  quotes: "인용문과 작가",
  transactions: "계좌 거래 — 출금 음수, 잔액 파생",
  paymentCards: "결제 카드 — Luhn 유효 번호, 마스킹",
  invoices: "청구서 — 항목 합계·세금·결제일",
  images: "picsum 이미지 — 크기·흑백·블러 변형",
},
};

const enUS: Nested = {
presetData: {
  companies:
    "Technovation, Digital Solutions, Smart Systems, Futuretech, Innovation Lab, Cloudworks, Data Insight, Next Generation, Global Soft, Creative Studio",
  jobTitles:
    "Frontend Developer, Backend Developer, Full-stack Developer, Data Engineer, DevOps Engineer, UI/UX Designer, Project Manager, Product Manager, QA Engineer, Systems Architect",
  lastNames:
    "Smith, Johnson, Williams, Brown, Jones, Garcia, Miller, Davis, Wilson, Moore",
  firstNames:
    "James, Olivia, Noah, Emma, Liam, Ava, Lucas, Mia, Ethan, Sofia",
  nameOrder: "given-first",
  industries:
    "IT Services, Manufacturing, Finance, Education, Healthcare, Consulting, Media",
  departments:
    "R&D, Sales, People, Finance, Customer Support, Product, Design, Quality",
  userStatuses: "Active, Invited, Dormant, Suspended",
  jobLevels: "Junior, Mid, Senior, Lead, Director",
  projectStatuses: "Planned, In progress, On hold, Done",
  productCategories:
    "Electronics, Apparel, Food, Furniture, Sports, Books, Beauty",
  orderStatuses: "Pending, Processing, Shipping, Delivered, Cancelled",
  roleNames: "Administrator, Editor, Viewer, Guest, Super administrator",
  roleDescriptions:
    "Full administrative rights, Can edit content, Read only, Limited access, Highest privileges",
  permissionNames:
    "View users, Manage users, View projects, Edit projects, Manage settings",
  permissionDescriptions:
    "Browse the user list, Create, edit and delete users, Browse projects, Edit projects, Change system settings",
  plans: "Free, Pro, Enterprise",
  cityName: "Springfield",
  districts: "North District, South District, East District, West District",
  engineStatuses: "Design, Build, Testing, Production, Discontinued",
  manufacturers:
    "Apex Components, Northline Electric, Cellworks, Mando Systems, Thermalcore",
  suppliers:
    "Wia Industrial, Daewon Spring, Sewon Precision, Hwashin Metal, Donghee Auto",
  partStatuses: "Normal, Discontinued, Under review, Awaiting approval",
  auditActions: "Create, Update, Delete, Permission change, Sign-in",
  departmentDescription: "The {name} department.",
  projectName: "Project {n}",
  productName: "Product {n}",
  productDescription: "A description of product {n}.",
  categoryDescription: "The {name} category",
  shippingAddress: "{district}, {city}",
  engineName: "Engine {n}",
  partName: "Part {n}",
  auditDescription: "Log for operation {n}",
  personName: "{first} {last}",
  localeId: "en",
  firstNamesMale: "James, Liam, Noah, Ethan, Lucas, Owen, Henry, Leo, Jack, Daniel",
  firstNamesFemale: "Emma, Olivia, Ava, Mia, Chloe, Zoe, Lily, Grace, Ella, Sophia",
  streets: "Main St, Oak Ave, Pine Rd, Maple Dr, Cedar Ln, Elm St, Lake View Rd, Park Ave",
  cities: "Springfield, Riverside, Fairview, Franklin, Clinton, Madison, Georgetown, Salem",
  regions: "CA, NY, TX, WA, IL, MA, CO, OR",
  country: "United States",
  postcodeFormat: "#####",
  phoneFormat: "(###) ###-####",
  cellFormat: "###-###-####",
  timezones: "-8:00, -7:00, -6:00, -5:00, +0:00, +1:00, +9:00",
  words: "lorem, ipsum, dolor, sit, amet, consectetur, adipiscing, elit, sed, do, eiusmod, tempor, incididunt, ut, labore, et, dolore, magna, aliqua, enim",
  productAdjectives: "Small, Ergonomic, Rustic, Sleek, Handmade, Modern, Compact, Premium",
  productMaterials: "Steel, Wooden, Cotton, Leather, Ceramic, Aluminum, Linen, Glass",
  productNouns: "Chair, Lamp, Keyboard, Bottle, Backpack, Speaker, Notebook, Watch",
  brands: "Apex, Nimbus, Orion, Vertex, Zenith, Lumen, Pixel, Cascade",
  availabilityStatuses: "In Stock, Low Stock, Out of Stock",
  reviewComments: "Exceeded expectations!, Works exactly as described., Shipping was fast., Great value for the price., Would buy again., Packaging could be better., Color differs slightly from the photo.",
  cuisines: "Korean, Italian, Mexican, Japanese, Indian, Thai, French, Chinese",
  mealTypes: "Breakfast, Lunch, Dinner, Snack, Brunch",
  dishes: "Bibimbap, Kimchi Stew, Pasta, Tacos, Ramen, Curry, Bulgogi, Risotto, Japchae, Tteokbokki",
  difficulties: "Easy, Medium, Hard",
  currency: "USD",
  merchants: "Coffee House, Grocery Mart, Book Store, Gas Station, Corner Shop, Food Delivery, Metro Transit, Online Store",
  transactionCategories: "Food, Transport, Shopping, Bills, Entertainment, Health, Education, Travel",
  transactionTypes: "debit, credit, refund",
  tags: "new, popular, sale, featured, limited, bestseller",
  todoTasks: "Write report, Prepare client meeting, Review PR, Plan sprint, Design review, Verify deployment, Update docs, Reconcile budget, Schedule interviews, Share meeting notes",
  priorities: "low, medium, high",
  quotes: "Simplicity is the ultimate sophistication., Stay hungry; stay foolish., Well begun is half done., A journey of a thousand miles begins with a single step., There is no end to learning., Never put off till tomorrow what you can do today., Failure is the mother of success., Knowledge is power.",
  quoteAuthors: "Leonardo da Vinci, Steve Jobs, Aristotle, Laozi, Confucius, Benjamin Franklin, Thomas Edison, Francis Bacon",
  colorNames: "Red, Blue, Green, Yellow, Purple, Orange, Gray, Black",
},
presetField: {
  id: "ID",
  isActive: "Active",
  num: "No.",
  name: "Name",
  email: "Email",
  phone: "Phone",
  company: "Company",
  jobTitle: "Job title",
  status: "Status",
  jobLevel: "Level",
  createdAt: "Created",
  roleName: "Role name",
  description: "Description",
  scope: "Scope",
  permissionList: "Permissions",
  permissionName: "Permission name",
  category: "Category",
  roleId: "Role ID",
  inviterId: "Inviter ID",
  expiresAt: "Expires",
  orgName: "Organization",
  industry: "Industry",
  domain: "Domain",
  plan: "Plan",
  orgId: "Organization ID",
  departmentName: "Department",
  managerId: "Manager ID",
  departmentId: "Department ID",
  projectName: "Project name",
  startDate: "Start",
  endDate: "End",
  budget: "Budget",
  client: "Client",
  visibility: "Visibility",
  productName: "Product",
  price: "Price",
  stock: "Stock",
  image: "Image",
  categoryName: "Category name",
  parentCategoryId: "Parent category ID",
  order: "Order",
  userId: "User ID",
  orderItems: "Line items",
  total: "Total",
  shippingAddress: "Ship to",
  orderedAt: "Ordered",
  projectId: "Project ID",
  engineName: "Engine",
  code: "Code",
  version: "Version",
  manufacturer: "Manufacturer",
  specifications: "Specs",
  engineId: "Engine ID",
  parentPartId: "Parent part ID",
  partName: "Part",
  partCode: "Part code",
  type: "Type",
  level: "Level",
  quantity: "Quantity",
  unit: "Unit",
  supplier: "Supplier",
  cost: "Cost",
  leadTime: "Lead time (days)",
  actorId: "Actor ID",
  entityType: "Entity type",
  entityId: "Entity ID",
  action: "Action",
  time: "Time",
  ipAddress: "IP address",
  allocation: "Allocation (%)",
  billable: "Billable",
  joinedAt: "Joined",
  lastActive: "Last active",
  title: "Title",
  body: "Body",
  tags: "Tags",
  coverImage: "Cover Image",
  likes: "Likes",
  dislikes: "Dislikes",
  views: "Views",
  publishedAt: "Published At",
  postId: "Post ID",
  author: "Author",
  task: "Task",
  completed: "Completed",
  priority: "Priority",
  dueDate: "Due Date",
  recipeName: "Recipe Name",
  cuisine: "Cuisine",
  mealType: "Meal Type",
  difficulty: "Difficulty",
  ingredients: "Ingredients",
  instructions: "Instructions",
  prepTime: "Prep Time (min)",
  cookTime: "Cook Time (min)",
  servings: "Servings",
  calories: "Calories per Serving",
  rating: "Rating",
  reviewCount: "Review Count",
  quote: "Quote",
  brand: "Brand",
  sku: "SKU",
  discount: "Discount (%)",
  availability: "Availability",
  weight: "Weight (kg)",
  dimensions: "Dimensions",
  thumbnail: "Thumbnail",
  images: "Images",
  slug: "Slug",
  cartProducts: "Cart Products",
  discountedTotal: "Discounted Total",
  totalProducts: "Total Products",
  totalQuantity: "Total Quantity",
  updatedAt: "Updated At",
  productId: "Product ID",
  comment: "Comment",
  gender: "Gender",
  reviewer: "Reviewer",
  reviewerEmail: "Reviewer Email",
  avatar: "Avatar",
  verifiedPurchase: "Verified Purchase",
  reviewDate: "Review Date",
  accountId: "Account No.",
  transactionType: "Transaction Type",
  amount: "Amount",
  currency: "Currency",
  merchant: "Merchant",
  balance: "Balance After",
  reference: "Reference",
  transactedAt: "Transacted At",
  cardholder: "Cardholder",
  cardType: "Card Type",
  cardNumber: "Card Number",
  cardNumberMasked: "Card Number (masked)",
  last4: "Last 4",
  expiry: "Expiry (MM/YY)",
  billingAddress: "Billing Address",
  isDefault: "Default Card",
  customer: "Customer",
  invoiceItems: "Invoice Items",
  subtotal: "Subtotal",
  taxRate: "Tax Rate",
  tax: "Tax",
  issuedAt: "Issued At",
  paidAt: "Paid At",
  picsumId: "Photo ID",
  width: "Width",
  height: "Height",
  url: "URL",
  grayscale: "Grayscale",
  blur: "Blur",
  previewUrl: "Preview URL",
  color: "Dominant Color",
  uploadedAt: "Uploaded At",
  userAgent: "User Agent",
  firstName: "First Name",
  lastName: "Last Name",
  username: "Username",
  birthDate: "Birth Date",
  age: "Age",
  cell: "Cell",
  street: "Street",
  city: "City",
  region: "State / Region",
  country: "Country",
  postcode: "Postcode",
  latitude: "Latitude",
  longitude: "Longitude",
  timezone: "Timezone",
  registeredAt: "Registered At",
  address: "Address",
  favorite: "Favorite",
  notes: "Notes",
  lastContactedAt: "Last Contacted",
  salary: "Salary",
  hireDate: "Hire Date",
  remote: "Remote",
},
presetMeta: {
  categoryUsersAuth: "Users, roles and permissions",
  categoryOrganization: "Organizations, departments and projects",
  categoryEcommerce: "Products, categories and orders",
  categoryManufacturing: "Products, parts and BOM",
  categorySystem: "System logs and memberships",
  users: "User records",
  roles: "Roles and permission groups",
  permissions: "Fine-grained permissions",
  invitations: "User invitations",
  organizations: "Organizations and companies",
  departments: "Departments",
  projects: "Projects",
  products: "Products",
  categories: "Product categories",
  orders: "Orders",
  engines: "Engines and products",
  components: "Parts and BOM",
  auditLogs: "System audit log",
  projectMembers: "Project memberships",
  categoryPeople: "Profiles, contacts and employees",
  categoryContent: "Posts, comments, todos, recipes and quotes",
  categoryFinance: "Transactions, payment cards and invoices",
  categoryMedia: "Image lists (picsum placeholders)",
  profiles: "Full profiles with matching name, gender and portrait",
  contacts: "Contacts — company and address partly blank",
  employees: "Employees — salary by level, manager reference",
  carts: "Carts — totals derived from items",
  reviews: "Product reviews — ratings skewed to 5",
  posts: "Posts with tags, reactions and views",
  comments: "Comments — post FK and author object",
  todos: "Todos — due date depends on completion",
  recipes: "Recipes with ingredients, steps and difficulty",
  quotes: "Quotes and authors",
  transactions: "Account transactions — debits negative, balance derived",
  paymentCards: "Payment cards — Luhn-valid numbers, masked",
  invoices: "Invoices — item totals, tax and paid date",
  images: "picsum images — size, grayscale and blur variants",
},
};

/** 인자 있는 문장 — 메인 카탈로그의 formattedMessages 와 같은 어법 */
const koFormatted: Record<string, (args?: PresetArgs) => string> = {
  "presetData.departmentDescription": (args) =>
    `${String(args?.name ?? "")} 부서입니다.`,
  "presetData.projectName": (args) => `프로젝트 ${String(args?.n ?? 0)}`,
  "presetData.productName": (args) => `상품 ${String(args?.n ?? 0)}`,
  "presetData.productDescription": (args) =>
    `상품 ${String(args?.n ?? 0)}에 대한 설명입니다.`,
  "presetData.categoryDescription": (args) =>
    `${String(args?.name ?? "")} 카테고리`,
  "presetData.shippingAddress": (args) =>
    `${String(args?.city ?? "")} ${String(args?.district ?? "")}`,
  "presetData.engineName": (args) => `엔진 ${String(args?.n ?? 0)}`,
  "presetData.partName": (args) => `부품 ${String(args?.n ?? 0)}`,
  "presetData.auditDescription": (args) =>
    `작업 ${String(args?.n ?? 0)}에 대한 로그`,
  "presetData.personName": (args) =>
    `${String(args?.last ?? "")}${String(args?.first ?? "")}`,
};

const enFormatted: Record<string, (args?: PresetArgs) => string> = {
  "presetData.departmentDescription": (args) =>
    `The ${String(args?.name ?? "")} department.`,
  "presetData.projectName": (args) => `Project ${String(args?.n ?? 0)}`,
  "presetData.productName": (args) => `Product ${String(args?.n ?? 0)}`,
  "presetData.productDescription": (args) =>
    `A description of product ${String(args?.n ?? 0)}.`,
  "presetData.categoryDescription": (args) =>
    `The ${String(args?.name ?? "")} category`,
  "presetData.shippingAddress": (args) =>
    `${String(args?.district ?? "")}, ${String(args?.city ?? "")}`,
  "presetData.engineName": (args) => `Engine ${String(args?.n ?? 0)}`,
  "presetData.partName": (args) => `Part ${String(args?.n ?? 0)}`,
  "presetData.auditDescription": (args) =>
    `Log for operation ${String(args?.n ?? 0)}`,
  "presetData.personName": (args) =>
    `${String(args?.first ?? "")} ${String(args?.last ?? "")}`,
};

function flatten(nested: Nested): Record<string, string> {
  const out: Record<string, string> = {};
  for (const [namespace, entries] of Object.entries(nested)) {
    for (const [key, value] of Object.entries(entries)) {
      out[`${namespace}.${key}`] = value;
    }
  }
  return out;
}

export const PRESET_STRINGS: Record<
  SupportedLocale,
  Record<string, PresetMessage>
> = {
  "ko-KR": { ...flatten(koKR), ...koFormatted },
  "en-US": { ...flatten(enUS), ...enFormatted },
};

const isSupported = (locale: string | undefined): locale is SupportedLocale =>
  locale === "ko-KR" || locale === "en-US";

/** locale 의 해소기 — 없는 키는 키 그대로 (fallback 판정이 그 위에서 돈다) */
export function resolvePresetTranslate(
  locale: string | undefined,
): PresetTranslate {
  const table = PRESET_STRINGS[isSupported(locale) ? locale : "en-US"];
  return (key, params) => {
    const value = table[key];
    if (typeof value === "function") return value(params);
    return typeof value === "string" ? value : key;
  };
}

/** React 밖 (AI tool 등) — 저장된 locale 로 */
export function presetTranslateFromStoredLocale(): PresetTranslate {
  return resolvePresetTranslate(getStoredLocale());
}
