-- ADR-201 참조 서버 메타 테이블 — H2 (Oracle 호환 모드, 개발·테스트). upload.jdbc.initSchema=h2 이면 기동 시 실행.
-- 컬럼 정의는 schema-oracle.sql 과 1:1. IF NOT EXISTS 는 H2 전용 (Oracle 은 DBA 가 1회 실행).

CREATE TABLE IF NOT EXISTS UPLOAD_SESSION (
  ID             VARCHAR(36)    NOT NULL,
  OWNER_ID       VARCHAR(128)   NOT NULL,
  FILE_NAME      VARCHAR(255)   NOT NULL,
  FILE_TYPE      VARCHAR(255),
  RELATIVE_PATH  VARCHAR(1024),
  TOTAL_SIZE     NUMBER(19)     NOT NULL,
  UPLOAD_OFFSET  NUMBER(19)     DEFAULT 0 NOT NULL,
  STORAGE_PATH   VARCHAR(1024)  NOT NULL,
  STATUS         VARCHAR(16)    NOT NULL,
  CREATED_AT     TIMESTAMP      NOT NULL,
  EXPIRES_AT     TIMESTAMP      NOT NULL,
  CONSTRAINT PK_UPLOAD_SESSION PRIMARY KEY (ID)
);

CREATE INDEX IF NOT EXISTS IX_UPLOAD_SESSION_OWNER   ON UPLOAD_SESSION (OWNER_ID, STATUS);
CREATE INDEX IF NOT EXISTS IX_UPLOAD_SESSION_EXPIRES ON UPLOAD_SESSION (EXPIRES_AT, STATUS);
