import { LIBRARY_CONTRACT_VERSION } from "./types";
import { buildCatalogLibrary } from "./library";

/** Read-only execution contract for the local Pencil direct-mapping fixtures. */
export function createPencilFixtureLibrary() {
  return buildCatalogLibrary({
    contractVersion: LIBRARY_CONTRACT_VERSION,
    revision: "adr248-pencil-fixture-v3-slot-typed",
    bindingIds: ["frame", "rectangle", "text", "group", "slot"],
    actionOpCodes: [
      "setState",
      "navigate",
      "callEndpoint",
      "toast",
      "capability",
    ],
    definitions: [
      {
        id: "lib:definition:frame",
        name: "Frame",
        mode: "native",
        bindingId: "frame",
        accepts: {},
        defaults: {},
        visual: {},
        stateRules: {},
      },
      {
        id: "lib:definition:rectangle",
        name: "Rectangle",
        mode: "native",
        bindingId: "rectangle",
        accepts: {},
        defaults: {},
        visual: {},
        stateRules: {},
      },
      {
        id: "lib:definition:text",
        name: "Text",
        mode: "primitive",
        bindingId: "text",
        accepts: { children: "string" },
        defaults: { children: "" },
        visual: {},
        stateRules: {},
      },
      {
        id: "lib:definition:group",
        name: "Group",
        mode: "native",
        bindingId: "group",
        accepts: {
          orientation: "string",
          size: "string",
          label: "string",
          role: "string",
          "aria-label": "string",
          "aria-labelledby": "string",
          isDisabled: "boolean",
          isInvalid: "boolean",
          isReadOnly: "boolean",
        },
        defaults: { orientation: "vertical", size: "M" },
        visual: { gap: 8 },
        propVisualRules: {
          size: { S: { gap: 6 }, M: { gap: 8 }, L: { gap: 12 } },
        },
        stateRules: {},
      },
      {
        id: "lib:definition:slot",
        name: "Slot",
        mode: "native",
        bindingId: "slot",
        accepts: { size: "string", description: "string" },
        propChoices: { size: ["S", "M", "L"] },
        defaults: { size: "M" },
        visual: {
          minHeight: 60,
          padding: 12,
          gap: 8,
          iconGap: 8,
          iconSize: 24,
          fontSize: 14,
          lineHeight: 1.5,
          radius: 6,
          fill: "#e5e5e5",
          fillAlpha: 0.5,
          borderColor: "#e5e7eb",
          borderWidth: 1,
          borderStyle: "dashed",
        },
        propVisualRules: {
          size: {
            S: { minHeight: 40, padding: 8, gap: 4, fontSize: 12, radius: 6 },
            M: { minHeight: 60, padding: 12, gap: 8, fontSize: 14, radius: 6 },
            L: {
              minHeight: 80,
              padding: 16,
              gap: 12,
              fontSize: 16,
              radius: 8,
            },
          },
        },
        stateRules: {},
      },
    ],
    templates: [],
    tokens: [],
  });
}
